### ISSUE TITLE
Documentation for Trinity.TSL.Compiler.exe

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#10]
Hello Trinity Team! So good to see you here on GitHub. Quick question for you; where can I find documentation of Trinity.TSL.Compiler.exe tool?

Tavi

**Comment by yatli** [comment]
Hi Tavi!

Currently the codegen is only meant to be used with the nuget package/vs extension. But we're considering to move the TSL bits onto Github. By then we should be able to get a list of parameters easy to explain. :)

**Comment by TaviTruman** [comment]
Hey Yatli thank you for the quick reply and explanation; I am writing a number of vs extensions instrumenting workflows for setup and deployment for service frabic deployment and test case code generation and codegen in support of a number of the design time workflows and my RDF/RDFS XML to TSL Parsers and generators. I look forward to learning more regarding a technical roadmap.

**Comment by yatli** [comment]
@TaviTruman  Added help text for Trinity.TSL.CodeGen.exe. See: https://github.com/Microsoft/GraphEngine/commit/cd304bfb61deef31342e722555f7501034f77f71#diff-8c4bd7c3e35b4ff955183f219eaa0c25R24
