### ISSUE TITLE
TSL module keyword

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#11]
@shaobin I see the "module" keyword in the LIKQ Fanoutsearch project; what is the "module" keyword do? Is there any documentation that describes the "module" keyword? It does not appear in any of the documentation that I have access to.

Tavi

**Comment by shaobin** [comment]
@TaviTruman "module" is a newly introduced TSL keyword. We've just updated the document: https://www.graphengine.io/docs/manual/TSL/tsl-basics.html#serverproxymodule   Thanks!

**Comment by TaviTruman** [comment]
@shaobin Thank you! I think that the "module" concept and keyword is a useful syntax/semantic sugar and provides more formal declaration and definition for "server" object in TSL; the client-side use of the server object is very clean - nice job!
