### ISSUE TITLE
How to install GraphEngine in a cluster?

### ISSUE THREAD

**Issue by khaledammar** [microsoft/GraphEngine#116]
Is there any documentation available for the installation procedure, hopefully for Ubuntu?

**Comment by bingzhangdai** [comment]
As far as I know, you can find some information from issue #114 and #62. I am also exploring the configuration process now.

**Comment by khaledammar** [comment]
@bingzhangdai thank you for the reference. I checked #114, but I could not find any documentation for the setup process?

**Comment by bingzhangdai** [comment]
Maybe [Distributed Hashtable ](https://www.graphengine.io/docs/manual/DemoApps/DistributedHashtable.html) example can be helpful. This example has one server though, you can do some configuration in ``` trinity.xml ``` to setup multiple servers and call ```TrinityConfig.LoadConfig()``` after that. Then you can start all the instances separately. They will automatically connect to each other.

**Comment by yatli** [comment]
update: the Service Fabric integration has been merged into `master`. I'm closing this issue now -- documentation will follow shortly.

**Comment by bingzhangdai** [comment]
大年初一还在工作，太可怕了😱

**Comment by yatli** [comment]
@bingzhangdai 过年好哇（

**Comment by bingzhangdai** [comment]
hh，春节快乐~（现在工作又不带薪，虽然在家也是挺无聊的 ╮(╯▽╰)╭
