### ISSUE TITLE
tsl codegen

### ISSUE THREAD

**Issue by bouyeijiang** [microsoft/GraphEngine#130]
how dose tsl generate code?

**Comment by TaviTruman** [comment]
The GE TSL to C# technology is written in C++, very powerful and expressive; it gets invoked during compile and build process in visual studio. It generates a bunch of coded files; DSL to access the memory cloud and the Client/Server code is generated as well.

**Comment by bouyeijiang** [comment]
how can i use tsl files generate c# code ? do you have use example?

**Comment by TaviTruman** [comment]
@bouyeijiang I am just now seeing your comment; give me a bit of time this morning and I'll put together some instructions; you can start with the sample (simple-code-sample) code here on the site. One particular aspect to consider is that the GE technology is very unique in that a DSL MemoryCloud API surface is machine generated for you based on your TSL design; that is why is considered to be a "computed" Graph technology. 

You'll find that the actual working, material, semantics of the TSL is presented back at you via the exposed API. The generated files are hidden in the output directory and the source and compiled assemblies are linked into your app. So as you access the API you are accessing the generated code. 

If you want to see beautiful, clean, creative, expert design and coding then take a look at the code generated; its special.

**Comment by TaviTruman** [comment]
@bouyeijiang I've been busy working on an new GE app in preparation for an up coming conference and demo there; I'll post sample code here for you in the next business day or so. Sorry for the delay.

**Comment by yatli** [comment]
Closing inactive issue. Feel free to reopen.
