### ISSUE TITLE
log4net integration

### ISSUE THREAD

**Issue by yatli** [microsoft/GraphEngine#132]

**Comment by Itfly** [comment]
I think you should use Microsoft.Extensions.Logging package, not specific logger
.

**Comment by yatli** [comment]
@ItFly thanks for the suggestion. Yes we do not intend to bind to a specific logger; I’m only hoping to keep the log hook really lean and mean, and all other logging facilities go through our p/invoked collector.

But you’re right, if the ms package already provides the adapters, the effort for building such is weaved
