### ISSUE TITLE
Question: Updating the official NuGet Package

### ISSUE THREAD

**Issue by nvankaam** [microsoft/GraphEngine#133]
I was running into an issue with SaveGenericCell, where it tells me that the object i am passing is not valid. When debugging with a custom compiled version of GraphEngine from this git repository the issue does not occur. I noticed the latest version of GraphEngine available on NuGet is 1.0.8482, which is over a year old: https://www.nuget.org/packages/GraphEngine.Core/

Will the recent updates be made available on NuGet any time soon?

**Comment by yatli** [comment]
@nvankaam hi!
Yes, the nuget package is a bit outdated and there has been various fixes and updates since then, with the most significant part being the TSL codegen reimplemented. It has been stabilized for a while and we will sign and update the package soon!

**Comment by nvankaam** [comment]
Good to hear, thanks!
