### ISSUE TITLE
multi_cell_lock: need explicit Transaction objects

### ISSUE THREAD

**Issue by yatli** [microsoft/GraphEngine#138]
In the current implementation, each thread has an implicit transaction context bound to the current thread TLS. However this approach has the following disadvantages:

- Performance decrease for non-transactional scenarios. Apart from our lock_cell/lock_hash/lock_db lock levels, we should additionally have non_transactional type (null tx object)
- Lock context disruption upon asynchronous continuation. The execution has been transferred to another thread, and the new thread does not have the original transaction in its TLS.
- Experiments show a significant performance impact, if we put the context in C# thread local/async local storage

This issue proposes an alternative approach, to provide both transactional/non-transactional support. To do so, we refactor thread-local context into transaction contexts, which can be nulled out in non-transactional scenarios. Therefore in the C# runtime the transaction handles can be plugged into any active thread, as long as there's no race conditions. The transaction object can be then preserved in closures automatically created in asynchronous routines, thus compatible with `await/async` pattern.

Since there's no race condition, it does not matter which thread is holding which transaction. A continuation may wake up to find the transaction in the closure is blocked, and it will enter the arbitration routine just like what we are currently doing for a threadcontext.

**Comment by TaviTruman** [comment]
@Yatao in the new listener class model I take care to make certain that object and entity creation takes on the same thread we work and or call on. I like your approach as it bring us into alignment with the SF programming model - leveraging await/async.

**Comment by yatli** [comment]
@tavitruman yep this is the reason that `multi_cell_lock` branch has been kept away from entering `master`.. I'm bringing it up and I will find time to make another attempt.

**Comment by yatli** [comment]
done.

**Comment by TaviTruman** [comment]
@yatli Most Excellent!
