### ISSUE TITLE
Is Graph Engine suitable for social network application?

### ISSUE THREAD

**Issue by garfeildma** [microsoft/GraphEngine#156]
Hi,
We are building a social app like Twitter & Weibo, and found that handling the relations are difficult. So we try to find something like [TAO](https://www.facebook.com/notes/facebook-engineering/tao-the-power-of-the-graph/10151525983993920/) by Facebook, finally found Graph Engine.
We want to user Graph Engine for the graph relation query, data persist in the MySql database. Currently, our largest table is the user following relation table which has 150 million rows.
So my questions are:

1.  is graph engine suitable for a social graph? Is there any use cases?
2.  how scalability graph engine could be? If data continues to increase, can graph engine handle more data by adding machines to the cluster? 
3.  how about the stability of graph engine, if one node down, how fast the data could be restored?
4.  is there any plan to support GraphQL?

thx

**Comment by akuckartz** [comment]
Why don't you use SPARQL ?

**Comment by akshayjh** [comment]
Have you tried neo4j? I would suggest to go through it.

**Comment by garfeildma** [comment]
@anonymous31173 
neo4j cluster is too expensive for us

**Comment by yatli** [comment]
hello @garfeildma , thanks for reaching out.
per your questions:

> is graph engine suitable for a social graph? Is there any use cases?

yes. we've got internal clusters running various computation tasks on social network datasets.

> how scalability graph engine could be? If data continues to increase, can graph engine handle more data by adding machines to the cluster?

GraphEngine is distributed, and the graph algorithms (traversal etc.) are implemented with message passing. By default the cluster is configured as share-nothing so the capacity scales linearly when you add machines.

> how about the stability of graph engine, if one node down, how fast the data could be restored?

We are actively working on availability features and it has recently come back into the master branch. We are now able to run the cluster in HA mode with no single-point-failure. Service recovery depends on how fast you can load your data back from the persistent storage to the memory.

> is there any plan to support GraphQL?

we have that on our backlog. a lot of stuff in GraphQL will naturally map to GE operations. If there is a strong request we will consider speed it up on this task.

**Comment by garfeildma** [comment]
@yatli thx, we can now design our application with GraphEngine now

**Comment by yatli** [comment]
closing the issue now. feel free to reopen or start a new issue for discussion. :)
