### ISSUE TITLE
Is there more LIKQ examples or documents?

### ISSUE THREAD

**Issue by BenDerPan** [microsoft/GraphEngine#161]
Is there more examples or documents about likq ?
What's the IDE tool in this [video](https://channel9.msdn.com/Blogs/Microsoft-Research-Asia/likq)?
Is that a official IDE tool use LIKQ for graph query ?

**Comment by chaosddp** [comment]
For me the unit test cases are better to learn

**Comment by BenDerPan** [comment]
@chaosddp  你的LIKQ例子跑起来了吗？方便发个例子参考下吗？我这边经常出现实例未初始化的异常，现在还不确定是不是异常。.NetCore的版本，我自己编译了一个，但是同样的未实例化异常，不太清楚哪里出了问题。

**Comment by chaosddp** [comment]
@BenDerPan 我可以正常跑，如果是.net core版本，要先Global.Cloud.Open(false)，之后的查询就不会异常，

**Comment by BenDerPan** [comment]
@chaosddp 感谢，我参考FreeBase 例子再试试。
