### ISSUE TITLE
Datastorage Misunderstanding

### ISSUE THREAD

**Issue by MrCorba** [microsoft/GraphEngine#166]
Goodafternoon!

I'm not sure if this is a bug or just some stupid misunderstanding from my end. I've got the code as below and it generates a working http interface. But I've got a problem with creating a new word that's driving me crazy.

**Steps**
1. Create("test") -> Returns { description: "test", id: 1 }
2. Get(1) -> "this does not exist"
3. Search("test") -> Returns { description: "test", id: 1 }
4. Update(1, "newTest") -> Returns { description: "newTest", id: 1 } 
5. Get(1) -> Returns { description: "newTest", id: 1 } 
6. Search("test") -> Returns { description: "test", id: 1 }

I looks like it uses 2 different datasets. I hope someone here can help me with this. 

Cheers!

```
public class WordsStore : GraphEngineModels.WordsStoreBase
    { 
        public override void GetHandler(GetRequest request, out Word response)
        {   
            try
            {
                response = Global.LocalStorage.LoadWord(request.word_id);
            }
            catch
            {
                response = new Word(description: "");
            }
        }

        public override void CreateHandler(CreateRequest request, out Word response)
        {
            Word newWord = new Word(description: request.word);

            Global.LocalStorage.SaveWord(newWord);

            response = newWord;
        }

        public override void UpdateHandler(Word request, out UpdateResponse response)
        {
            if (Global.LocalStorage.SaveWord(request))
                response.message = "OK";
            else
                response.message = "FAIL";
        }

        public override void SearchHandler(SearchRequest request, out Word response)
        {
            List<long> ids = Index.SubstringQuery(Index.Word.description, request.query);

            if (ids.Count > 0)
            {
                response = Global.LocalStorage.LoadWord(ids[0]);
            }
            else
            {
                response = new Word();
            }
        }
}
```

**Comment by yatli** [comment]
hi!

Try this:

```
//   Word newWord = new Word(description: request.word);
Word newWord = new Word(request.id, description: request.word);
```

**Comment by MrCorba** [comment]
Thanks for the fast reply!

You mean in the CreateHandler method right?

Because at the moment of creation I don't have an id yet. That request only consists of a description, the id is created by GraphEngine.

**Comment by yatli** [comment]
In your `GetHandler`, could you log down the exception? Doesn't look like it will return "this does not exist" but anyway, the concrete exception message will help.

**Comment by MrCorba** [comment]
It throws the following exception:

`Trinity.Storage.CellNotFoundException: 'The cell with id = 1612020407969715500 not found.'`

I tried to create the word **test** and then tried to get the id returned by the `CreateHandler`

**Comment by yatli** [comment]
that doesn't look like a '1' to me :)
you created a cell with id 1, search handler is good so it's definitely there; however, in the get handler the system complains about a weird id.
how did you supply word_id at the sender side?

**Comment by MrCorba** [comment]
The '1' in my original example was just a simple number, to prevent typing complete typing the 32-bit ID's from GE;)

I didn't supply an ID with the `CreateHandler`. I just sent `{ description: "test" }`. And by calling `Word newWord = new Word(description: request.description)` I get a new Word with the corresponding ID. The ID created by GE.

Then I copy that ID and sent a request to the `GetHandler`. Then it throws that exception.

The `1612020407969715500` is the ID I get from GE.

**Comment by yatli** [comment]
right, by default it will create a random cellId. but I'm not connecting the dots together without getting more information.
can you supply your tsl? I can try a minimal repro at my end.
there might be some issues if you use a cell type as the out argument in a http handler.

**Comment by yatli** [comment]
also, does it happen to every word, or some particular ones?
if it's happening to every word, I suggest you hard code some cell ids to check if GE really forgets what you force it to remember.

**Comment by MrCorba** [comment]
I understand the random cellid, but doesn't that get persisted on SaveWord?

It happens with every word, with the ID generation by GE. If I use the `UpdateHandler` and supply a own ID, the `GetHandler` finds it. 

But that still doesn't make sense why the `SearchHandler` can find it and return the same ID as the `CreateHandler`.

This is my tsl
```
cell Struct Word
{	
	[Index]	
	string description;
}

struct GetRequest
{
    long word_id;
}

protocol Get
{
    type:HTTP;
    request:GetRequest;
    response:Word;
}

struct UpdateResponse
{
    string message;
}

protocol Update
{
    type:HTTP;
    request:Word;
    response:UpdateResponse;
}

struct CreateRequest 
{
	string word;	
}

protocol Create
{
	type:HTTP;
	request:CreateRequest;
	response:Word;
}

struct SearchRequest
{
	string query;	
}

protocol Search
{
	type:HTTP;
	request:SearchRequest;
	Response:Word;
}

server WordsStore
{
    protocol Get;
    protocol Create;
    protocol Update;
    protocol Search;
}
```

**Comment by MrCorba** [comment]
If I change the `CreateHandler` to input a Word with an id, it does save the Word with that ID and the `GetHandler` finds the word with the corresponding id. And the `SearchHandler` finds it aswell.

**Comment by yatli** [comment]
We've got a special implementation for transmitting cells on wire -- CellId is not a part of the cell buffer for those in the storage (ids are stored in the metadata), but I'm not entirely sure how's things handled in a Http handler..

Could you try, log down the CellId in the create handler, and compare it to what you have as a response?

**Comment by yatli** [comment]
We're getting close. Your understanding is absolutely correct, it's some stupid bug in the system. :)

**Comment by MrCorba** [comment]
Long live bugs!

The ID in the `CreateHandler` is the same as the returned ID. 

I've even tried Refetching the word before returning the ID and that returns the same result.

**Comment by yatli** [comment]
Okay, so it's not a faulty id.
I'd then suggest separate the problem: create a minimal repro

**Comment by yatli** [comment]
If it fails, it doesn't matter if it fails in a handler, or in our "lab condition".
More test is fun :)

**Comment by MrCorba** [comment]
I've created a minimal version of this, with only the Create and Get. It still has the same problem.

[It can be found here](https://github.com/MrCorba/GraphEnginetest)

**Comment by MrCorba** [comment]
Woops wrong button

**Comment by yatli** [comment]
Thanks for the minimal repro! I'll experiment away with it.

**Comment by yatli** [comment]
Running on version `1.0.9083`, my minimal repro:
```
using Trinity;

namespace Issue166
{
    class Program
    {
        static void Main(string[] args)
        {
            Word w = new Word(description: "hello");
            Console.WriteLine(w.ToString());
            var err = Global.LocalStorage.SaveWord(w);
            Console.WriteLine(err);
            Console.WriteLine(Global.LocalStorage.LoadWord(w.CellID).ToString());
        }
    }
}
```

Running result:
```
{"CellID":5528019624763900652,"description":"hello"}
[ INFO    ] LogLevel set to [ INFO    ]
[ INFO    ] Loading Graph Engine Extensions.
[ INFO    ] Scanning for TSL storage extension.
[ INFO    ] TSL storage extension loaded.
[ INFO    ] Scanning for MemoryCloud extensions.
[ INFO    ] No MemoryCloud extension found.
[ INFO    ] Scanning for startup tasks.
[ INFO    ] LocalMemoryStorage is initialized in read-write mode
[ INFO    ] Initializing logging facility
[ INFO    ] Reading log file.
[ INFO    ] Write-ahead-log successfully loaded. Recovered 0 records.
[ INFO    ] Creating write-ahead log file c:\users\yatao\source\repos\Issue166\Issue166\bin\Debug\storage\B\write_ahead_log\primary_storage_log_0.dat
True
{"CellID":5528019624763900652,"description":"hello"}
Press any key to continue . . .
```

So.. no repro on my side.
Can you try building a fresh package from `master`? Maybe the bug is now history :D

**Comment by MrCorba** [comment]
That would be awesome. Unfortunately I can't check at the moment but I'll check first  thing in the morning.

Although, when I did the `LoadWord` inside the `CreateHandler` it did find the word. But we'll see tomorrow!

**Comment by MrCorba** [comment]
Sorry for the long wait. Had some trouble building from master with VS dependencies;)

I build the master and tried your example, no problem whatsoever. But that same repro did work on the NuGet master;)

But when I try to build the HTTP server from this it keeps giving error messages like this
`The type 'TrinityServer' is defined in an assembly that is not referenced. You must add a reference to assembly 'Trinity.Core, Version=1.0.8482.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.	`

So I haven't been able to test this with the HTTP version.

**Comment by yatli** [comment]
hmm. that's definitely some nuget package versioning issue. please try uninstall the packages from your project, and install the latest version again.

**Comment by MrCorba** [comment]
Still the same problem, I'm not sure if this is the problem with the NuGet packages and the VSExtension running out of sync.

**Comment by yatli** [comment]
ooooh @MrCorba you're using a .tproj? Try move the tsl to the C# main project, and then delete the tproj

**Comment by MrCorba** [comment]
Do I need extra references/packages if I do that? Because now my Graph project isn't recognizing the structs in the tsl file.

**Comment by yatli** [comment]
in solution explorer, select the tsl file in your C# project, look into "properties" pane, and set Build Type to `TslCodegen`.

**Comment by MrCorba** [comment]
Thanks, I can start the server again. But again when I create a Word, I can't get it with the ID returned by the method. 

NuPackage version Core/LIKQ = 1.0.9083
.NET = 4.6.1

**Comment by MrCorba** [comment]
The following code in the `CreateHandler` works, so the word is saved to the Graph

```
public override void CreateHandler(CreateRequest request, out Word response)
        {
            Word newWord = new Word(description: request.word);

            Global.LocalStorage.SaveWord(newWord);
            
            Word returnWord = Global.LocalStorage.LoadWord(newWord.CellID);

            response = returnWord;
        }`

**Comment by MrCorba** [comment]
I found the problem! The id is somewhere in the transformation to the HTTP truncated. It only differs a tiny bit, so I've probably overlooked it. I guess the long is to long for the request...

Ah well, I'll see if I can figure out a solution for this. 

Thanks for your help man! GE is working as it should;)

**Comment by MrCorba** [comment]
Found also the location of the truncation, JSON.stringify in the default frontend of the server. The Max Integer for JS is not big enough to handle this.

```
var a = -8149189880332139626;

console.log(JSON.stringify(a)); // "-8149189880332140000"
```

**Comment by yatli** [comment]
such pitfall.. I'm glad you sorted this out! JSON specifies that a number is `-?[1-9]\d*` with arbitrary length, but on the javascript side you have https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

Let's close this issue for now. Let me know if you have further problems. Reopen or new issues are welcome.
