### ISSUE TITLE
Freebase-likq sample issues

### ISSUE THREAD

**Issue by PhilPJL** [microsoft/GraphEngine#167]
Latest code has build error:

Error	CS0535	'CellGroupAccessor' does not implement interface member 'ICellAccessor.Deserialize()'	freebase-likq	
...\Source\Repos\GraphEngine\samples\freebase-likq\freebase-likq\FreebaseAdapter.cs	166	

And line 131 in program.cs
            ZipFile.ExtractToDirectory("freebase-full-dataset.zip", Global.MyAssemblyPath);

should be
            ZipFile.ExtractToDirectory(s_freebase_dataset, Global.MyAssemblyPath);

**Comment by yatli** [comment]
On it.

**Comment by yatli** [comment]
@PhilPJL thank you for reporting this! I've pushed a patch to solve this. Please have a look.
