### ISSUE TITLE
FanoutSearch.FanoutSearchQueryException  Syntax error + Expecting 'VisitNode'

### ISSUE THREAD

**Issue by BenDerPan** [microsoft/GraphEngine#170]
My Environment:
VS2015 update3
GraphEngine.Core 1.0.8482.0 (From Nuget.org)
GraphEngine.LIKQ 1.0.8784.0  (From Nuget.org)

# Problem 1, In LambdaDSL.Evaluate method,  If I give StartFrom a start node object instead of the long cellid, everyting is ok, but when I give it a long cellid, the exception throw.
### My Code Part:
long cellid = HashHelper.HashString2Int64(startNode.Name);
var query = "MAG.StartFrom(3841074542558778930).FllowEdge(\"Friends\").VisitNode(Action.Return);";
var result = LambdaDSL.Evaluate(query);

### It throw the exception as below:
_“FanoutSearch.FanoutSearchQueryException”类型的未经处理的异常在 FanoutSearch.dll 中发生 
其他信息: Expecting 'VisitNode': MAG.StartFrom(3841074542558778930).FllowEdge("Friends")_

# Problem 2, In mod.LambdaQuery method, if I give StartFrom a positive number cellid value, it's ok. but when I give it a negative number of cellid value, the exception throw. I use HashHelper.HashString2Int64(node.Name) to generated the cellid, some id are positive and some are negative.
### My Code Part:
`
 var query2 = @"
MAG
  .StartFrom(new List<long>{-6320363468015968671})
  .FollowEdge(""Friends"")
  .VisitNode(Action.Return,new List<string>{""Name""});
";
var mod = Global.CommunicationInstance.GetCommunicationModule<FanoutSearchModule>();
var data=mod.LambdaQuery(query2);`
### It throw the exception as below:
_“FanoutSearch.FanoutSearchQueryException”类型的未经处理的异常在 FanoutSearch.dll 中发生 
其他信息: Syntax error: -6320363468015968671_

**Comment by chaosddp** [comment]
1. Typo issue: should be FollowEdge
2. Seems like a bug, using id instead of List<long> will be fine.

Also personally i suggest you using Likq for begining, it is fast and with IDE intellisense.

**Comment by yatli** [comment]
Thanks for reporting, and that definitely looks like a bug!
I will look into this after I got my tests up and running. @chaosddp I think we should change the assembly name to match the package name as a workaround. What do you think?

**Comment by chaosddp** [comment]
Yes, it would be better, since it only repro on netcore.

**Comment by BenDerPan** [comment]
@chaosddp Thank you for your suggest very much 👍:) , I know linq is much more better, and I tested with linq, it's fast and easy to write, but LIKQ is much more than linq, because I want to make it work with python and golang. Though http protocol can do that, but I have to define a lot of protocol and implement with C# backend, that's terrible for me, so, I think LIKQ is much more better, and I wish LIKQ will be better and stronger.

**Comment by yatli** [comment]
Update: it happens only if you pass in a List<long> with negative ids.

Good:
```
        [Theory]
        [InlineData(-1)]
        [InlineData(-15)]
        [InlineData(-6256)]
        [InlineData(-6486119)]
        [InlineData(-4502847529)]
        [InlineData(-534913639468)]
        [InlineData(1)]
        [InlineData(15)]
        [InlineData(6256)]
        [InlineData(6486119)]
        [InlineData(4502847529)]
        [InlineData(534913639468)]
        public void StartFrom_Id_List_Single(long origin)
        {
            var fs_desc = LambdaDSL.Evaluate($@"MAG.StartFrom({origin})");
        }
```

Bad:
```
        [Theory]
        // all negative
        [InlineData(-1, -54519)]
        [InlineData(-15, -5845)]
        [InlineData(-6256, -81)]
        [InlineData(-6486119, -7451, -157478)]
        [InlineData(-4502847529, -7572457146, -756134)]
        [InlineData(-534913639468, -6496187346913, -1, -62456, -464143)]
        // all positive
        [InlineData(1, 54519)]
        [InlineData(15, 5845)]
        [InlineData(6256, 81)]
        [InlineData(6486119, 7451, 157478)]
        [InlineData(4502847529, 7572457146, 756134)]
        [InlineData(534913639468, 6496187346913, 1, 62456, 464143)]
        // mixed
        [InlineData(1, -54519)]
        [InlineData(-15, 5845)]
        [InlineData(6256, -81)]
        [InlineData(-6486119, 7451, -157478)]
        [InlineData(4502847529, -7572457146, 756134)]
        [InlineData(-534913639468, 6496187346913, -1, 62456, -464143)]
        public void StartFrom_Id_List_Multi(params long[] origin)
        {
            var fs_desc = LambdaDSL.Evaluate($@"MAG.StartFrom(new List<long>{{{string.Join(",", origin)}}})");
        }
```

**Comment by yatli** [comment]
@chaosddp @BenDerPan could you please help to test this out? If there are still problems, feel free to reopen or file a new issue.

**Comment by BenDerPan** [comment]
great ，I will test it later today.

**Comment by BenDerPan** [comment]
@yatli  Build failed with .netcore2.0 , now I am try to setup a windows build environment with windows SDK installed.
Error as below, I think it's the problem of .csproj ,that's  incompatible with .netcore:

`Core/QueryPredicateCompiler.cs(12,22): error CS0234: The type or namespace name 'Caching' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?) [/home/coder/Documents/Github/GraphEngine/src/Modules/LIKQ/FanoutSearch/FanoutSearch.csproj]
Core/QueryResultCache.cs(13,22): error CS0234: The type or namespace name 'Caching' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?) [/home/coder/Documents/Github/GraphEngine/src/Modules/LIKQ/FanoutSearch/FanoutSearch.csproj]
Core/QueryPredicateCompiler.cs(23,17): error CS0246: The type or namespace name 'MemoryCache' could not be found (are you missing a using directive or an assembly reference?) [/home/coder/Documents/Github/GraphEngine/src/Modules/LIKQ/FanoutSearch/FanoutSearch.csproj]
Core/QueryPredicateCompiler.cs(27,26): error CS0246: The type or namespace name 'CacheItemPolicy' could not be found (are you missing a using directive or an assembly reference?) [/home/coder/Documents/Github/GraphEngine/src/Modules/LIKQ/FanoutSearch/FanoutSearch.csproj]
Core/QueryResultCache.cs(39,17): error CS0246: The type or namespace name 'MemoryCache' could not be found (are you missing a using directive or an assembly reference?) [/home/coder/Documents/Github/GraphEngine/src/Modules/LIKQ/FanoutSearch/FanoutSearch.csproj]
Core/QueryResultCache.cs(43,17): error CS0246: The type or namespace name 'CacheItemPolicy' could not be found (are you missing a using directive or an assembly reference?) [/home/coder/Documents/Github/GraphEngine/src/Modules/LIKQ/FanoutSearch/FanoutSearch.csproj]
`

**Comment by chaosddp** [comment]
@BenDerPan i just make a PR to fix this. #175

**Comment by chaosddp** [comment]
@yatli passed on my Ubuntu, also with a PR to fix issues.

**Comment by yatli** [comment]
@chaosddp thanks!! I've made a few adjustments, `GraphEngine.LIKQ` package should target `netstandard2.0` not `netcoreapp2.0`. I've made sure it works on Windows. I guess the change won't break your build :)

**Comment by chaosddp** [comment]
@yatli yes, build passed, but with a typo issue, should be CellID: https://github.com/Microsoft/GraphEngine/blob/a5276c9d9f61a9a34032e34aa565918d5d529770/src/Modules/LIKQ/FanoutSearch/QueryLanguage/Verbs.cs#L38

**Comment by yatli** [comment]
oh sorry I messed it up.
I'm preparing for GE 2.0 release and we are going to deprecate all occurances of `CellID` and refactor to `CellId`.

**Comment by BenDerPan** [comment]
@yatli  I changed the Verbs.cs withCellID,  and build the .netcore version, I tested LINQ and LIKQ with C# ,   it works now, but the http server of LIKQ will never started although it logs out that server started , I check the listening port, the port is closed. I can't query it with restfull API .

`[ DEBUG   ] Sync (rsp) message 2 is registered.
[ DEBUG   ] Sync (rsp) message 3 is registered.
[ DEBUG   ] Async message 0 is registered.
Working Directory: /home/coder/Documents/NetCore/LIKQ-Examples/People-LIKQ/bin/Debug/netcoreapp2.0/
[ INFO    ] Trinity Assembly Path: /home/coder/Documents/NetCore/LIKQ-Examples/People-LIKQ/bin/Debug/netcoreapp2.0/

StorageRoot : /home/coder/Documents/NetCore/LIKQ-Examples/People-LIKQ/bin/Debug/netcoreapp2.0/storage/
LogDirectory: /home/coder/Documents/NetCore/LIKQ-Examples/People-LIKQ/bin/Debug/netcoreapp2.0/trinity-log
LoggingLevel: Debug
HttpPort:     80


[ INFO    ] Server 0 is successfully started.

[ INFO    ] Index: updating substring index of People_Name
`

=========================================================
# Updated 2018-03-22 

I fixed this by adding a http protocol with a server define in my tsl file, then I registed FanoutSearchModule with my server instead  TrinityServer, and It works, that's different when run it on Windows. Is that a bug?

**Comment by BenDerPan** [comment]
@yatli  The windows version I build with windows SDK 10.0.16299.0 (./tools/build.ps1) , build successfully with no error, but there is no LIKQ NuGet package generated, my output directory files as the pic below:
![image](https://user-images.githubusercontent.com/10903567/37701957-f34724ea-2d2b-11e8-92b0-4b8316939bd2.png)

**Comment by yatli** [comment]
@BenDerPan could you please attach your build log? I'll take a look

**Comment by BenDerPan** [comment]
@yatli  I search all "CellId" in the LIKQ solution(not only in Verbs.cs) and changed it to CellID, then rebuid it, it's now generated LIKQ package, but there is a new problem as below, I don't know why it still need the 1.0.8482.0 version, there should be 1.0.9083.0:
![default](https://user-images.githubusercontent.com/10903567/37704973-70363e88-2d35-11e8-92c7-771395adeb00.png)


![default](https://user-images.githubusercontent.com/10903567/37704724-96bae1c2-2d34-11e8-9843-252848dff89d.png)

I think you put a prebuild package to nuget.org is much better, I wonder my build environment is not set correctly.

**Comment by yatli** [comment]
@BenDerPan please try remove the offending packages from your project and try add them again.
Yeah we should release it to nuget... We have an internal process for release management, hang on tight while we make our way through it.. :)

**Comment by BenDerPan** [comment]
@yatli I think I found the problem , due to the GraphEngnie template, the template still use the old version, and everytime I try to build the project , VS will copy Trinity.Core.dll from $TrinityPath. 
How can I  build graphengine application from a empty project on windows vs without template? I know it's easy to do that with .netcore.

**Comment by chaosddp** [comment]
Just create a class library project, create a .tsl file, then mark it as TslCodeGen as following:  
```
  <ItemGroup>
    <TslCodeGen Include="MyTSL.tsl" />
  </ItemGroup>
```
then add GE package dependency.

**Comment by BenDerPan** [comment]
@chaosddp  that's not complete work on windows , I build the TSL model project success, but when I use it in my app project, I can not find the methods like Global.LocalStorage.SaveXXX(); XXX is my model entity. there are only methods like Global.LocalStorage.SaveCell();Global.LocalStorage.SaveGenericCell();

**Comment by chaosddp** [comment]
If your add correct namespace, then it may caused that your tsl project not build correctly, you can have a check if there is a folder "GeneratedCode" under 'obj' folder of your model project, if no, then you do not setup your project correct.

**Comment by yatli** [comment]
@BenDerPan try keyboard shortcut `Ctrl+.` on the red-swiggled method, it will prompt you to add the correct namespace.

**Comment by BenDerPan** [comment]
@yatli @chaosddp  there is no prompt and it generated the  code... 
![default](https://user-images.githubusercontent.com/10903567/37762994-d61859fc-2df8-11e8-8e99-be1013f2e72b.png)

![default](https://user-images.githubusercontent.com/10903567/37763178-553ccb46-2df9-11e8-981f-ccd7ee4b377a.png)

![default](https://user-images.githubusercontent.com/10903567/37763190-60db3fd2-2df9-11e8-8c71-0525cab6161c.png)


![default](https://user-images.githubusercontent.com/10903567/37763202-6cba7174-2df9-11e8-8ad6-7d27c6e9d137.png)


![default](https://user-images.githubusercontent.com/10903567/37763020-ee23d422-2df8-11e8-9210-18f4934d5cc0.png)
