### ISSUE TITLE
The target "pack" does not exist in the project. (GraphEngine.ServiceFabric)

### ISSUE THREAD

**Issue by bidiudiu** [microsoft/GraphEngine#179]
Hi,
  When I build GE on win10/VS2017, the error happens:
![image](https://user-images.githubusercontent.com/16871670/37821745-6b05b6f6-2ebf-11e8-9cbf-308626cd9f5f.png)
  Any tips on how to solve it? Thanks!

**Comment by bidiudiu** [comment]
btw, in "GraphEngine.ServiceFabric.sln", "Trinity.ServiceFabric.SampleApplication\Trinity.ServiceFabric.SampleApplication.sfproj" is a clerical error.

**Comment by yatli** [comment]
@bidiudiu hi! we're aware of this problem. If we use the new `csproj` format, we can specify `<IsPackable>false</IsPackable>` -- I will convert this project later.

As for the build, I think this won't be an issue, and will be ignored.

**Comment by yatli** [comment]
You'll have to install ServiceFabric SDK to build the SF packages ;)

**Comment by bidiudiu** [comment]
I see, Thanks yatli!
