### ISSUE TITLE
Question: Can I use linq or likq from the client side in distributed clusters situation?

### ISSUE THREAD

**Issue by BenDerPan** [microsoft/GraphEngine#185]
I wonder if GE supports use linq or likq in distributed clusters ? 
Thanks.

**Comment by yatli** [comment]
hi @BenDerPan, LIKQ fully supports distributed mode; For LINQ, we need to implement custom IQueryable to do scatter/gather.

**Comment by BenDerPan** [comment]
Hi@yatli, Is there any examples with implement custom IQueryable interface? Now I am going to try the LIKQ first. :)

**Comment by yatli** [comment]
@BenDerPan it's right in the TSL generated code :)
We implemented a bunch of IQueryable components for PLINQ and index. You can write a TSL file, compile it and take a look at obj/GeneratedCode

**Comment by BenDerPan** [comment]
@yatli  wonderful! thanks.
