### ISSUE TITLE
.NetCore version generating excep[tion Trinity.Client.TestServer 

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#186]
'dotnet.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Private.CoreLib.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'L:\IKW GE Dev\src\Modules\GraphEngine.Client\Trinity.Client.TestServer\bin\Release\netcoreapp2.0\Trinity.Client.TestServer.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Runtime.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'L:\IKW GE Dev\src\Modules\GraphEngine.Client\Trinity.Client.TestServer\bin\Release\netcoreapp2.0\Trinity.Client.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\lib\netstandard2.0\Trinity.Core.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\netstandard.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Net.HttpListener.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'L:\IKW GE Dev\src\Modules\GraphEngine.Client\Trinity.Client.TestServer\bin\Release\netcoreapp2.0\Trinity.Client.TestProtocols.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Linq.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Console.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Threading.Thread.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Collections.Concurrent.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Collections.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Threading.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Runtime.Extensions.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Diagnostics.StackTrace.dll'. Symbols loaded.
Exception thrown: 'System.DllNotFoundException' in Trinity.Core.dll
Exception thrown: 'System.TypeInitializationException' in Trinity.Core.dll
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Reflection.Metadata.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.IO.FileSystem.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Collections.Immutable.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Runtime.InteropServices.dll'. Symbols loaded.
Exception thrown: 'System.TypeInitializationException' in Trinity.Core.dll
An unhandled exception of type 'System.TypeInitializationException' occurred in Trinity.Core.dll
The type initializer for 'Trinity.Diagnostics.Log' threw an exception.

'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.6\System.Text.Encoding.Extensions.dll'. Symbols loaded.
The program '[30972] dotnet.exe' has exited with code 0 (0x0).
The program '[30972] dotnet.exe: Program Trace' has exited with code 0 (0x0).

**Comment by TaviTruman** [comment]
When I configure the projects to execute against .net461 in VS then all is well; by default it looks like the projects are defaulting to "dotnetcore20."

**Comment by yatli** [comment]
looks like an assembly loading problem. could you please show the content of your %USERPROFILE%\.nuget\packages\GraphEngine.Core folder?

**Comment by TaviTruman** [comment]
![image](https://user-images.githubusercontent.com/5692812/38655236-694987da-3dc8-11e8-87b6-6dfb5d1a0004.png)
![image](https://user-images.githubusercontent.com/5692812/38655259-858b0752-3dc8-11e8-81c4-72e55d7043f7.png)
![image](https://user-images.githubusercontent.com/5692812/38655290-a9baefe8-3dc8-11e8-8470-7d1be41b6f3b.png)

**Comment by yatli** [comment]
content of runtimes then?

**Comment by yatli** [comment]
with powershell you can do it with: `Get-ChildItem -Recurse`

**Comment by TaviTruman** [comment]
Directory: C:\Users\Tavi\.nuget\packages\graphengine.core


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2018     20:32                1.0.9083
d-----        3/29/2018     20:39                2.0.9328


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\1.0.9083


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2018     20:32                build
d-----        3/29/2018     20:32                content
d-----        3/29/2018     20:32                lib
d-----        3/29/2018     20:32                runtimes
d-----        3/29/2018     20:32                tools
-a----        3/29/2018     20:32        2352771 graphengine.core.1.0.9083.nupkg
-a----        3/29/2018     20:32             88 graphengine.core.1.0.9083.nupkg.sha512
-a----        3/29/2018     20:32           1210 graphengine.core.nuspec


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\1.0.9083\build


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/22/2018     10:54           1593 GraphEngine.Core.props
-a----        3/22/2018     11:43           3496 GraphEngine.Core.targets


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\1.0.9083\content


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/22/2018     11:43          25997 TrinityConfig.Schema.xsd


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\1.0.9083\lib


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2018     20:32                net451
d-----        3/29/2018     20:32                netstandard2.0


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\1.0.9083\lib\net451


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/29/2018     20:32        1083392 Trinity.Core.dll


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\1.0.9083\lib\netstandard2.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/29/2018     20:32         271872 Trinity.Core.dll


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\1.0.9083\runtimes


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2018     20:32                linux-x64
d-----        3/29/2018     20:32                win-x64


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\1.0.9083\runtimes\linux-x64


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2018     20:32                native


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\1.0.9083\runtimes\linux-x64\native


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/22/2018     10:54        1005752 libTrinity.so


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\1.0.9083\runtimes\win-x64


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2018     20:33                native


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\1.0.9083\tools


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/22/2018     10:54        4337512 Trinity.TSL.CodeGen
-a----        3/29/2018     20:32        1118208 Trinity.TSL.CodeGen.exe


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2018     20:39                build
d-----        3/29/2018     20:39                content
d-----        3/29/2018     20:39                lib
d-----        3/29/2018     20:39                runtimes
d-----        3/29/2018     20:39                tools
-a----        3/29/2018     20:39        2985557 graphengine.core.2.0.9328.nupkg
-a----        3/29/2018     20:39             88 graphengine.core.2.0.9328.nupkg.sha512
-a----        3/25/2018     09:14           1674 graphengine.core.nuspec


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\build


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/25/2018     15:36           1593 GraphEngine.Core.props
-a----        3/25/2018     16:04           3496 GraphEngine.Core.targets


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\content


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/25/2018     16:04          25997 TrinityConfig.Schema.xsd


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\lib


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2018     20:39                net451
d-----        3/29/2018     20:39                net461
d-----        3/29/2018     20:39                netstandard2.0


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\lib\net451


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/25/2018     16:14        1140224 Trinity.Core.dll


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\lib\net461


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/25/2018     16:14        1140224 Trinity.Core.dll


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\lib\netstandard2.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/25/2018     16:14         275968 Trinity.Core.dll


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\runtimes


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2018     20:39                linux-x64
d-----        3/29/2018     20:39                win-x64


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\runtimes\linux-x64


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2018     20:39                native


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\runtimes\linux-x64\native


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/25/2018     16:04        1402408 libTrinity.so


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\runtimes\win-x64


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/30/2018     19:56                native


    Directory: C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\tools


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/25/2018     16:04        4341608 Trinity.TSL.CodeGen
-a----        3/25/2018     16:14        1123840 Trinity.TSL.CodeGen.exe

**Comment by yatli** [comment]
`Trinity.dll` is missing in `C:\Users\Tavi\.nuget\packages\graphengine.core\2.0.9328\runtimes\win-x64`

**Comment by yatli** [comment]
you can remove the 2.0.9328 folder and let it restore automatically

**Comment by TaviTruman** [comment]
Problem resolved after manually deleting nuget\packages\graphengine.core\2.0.9328; I re-ran the build.ps1 script and now both .net native and .netcore20 executables run normally.

**Comment by yatli** [comment]
cool. :)
