### ISSUE TITLE
System.TypeInitializationException: The type for Trinity.Global threw an exception

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#188]
I can build the freebase-likq sample but I get this error when I try to run the .NET 4.6.1 version:

![image](https://user-images.githubusercontent.com/5692812/39102380-2bde32b8-4658-11e8-8c94-ceda6a90bbb0.png)

**Comment by yatli** [comment]
hi Tavi, please make sure you build it with x64 arch.

**Comment by TaviTruman** [comment]
@yatli  hey Yatao! Yikes - I thought I was; my bad.

**Comment by yatli** [comment]
There might still be a few issues -- especially the sqlite part; let me know if you encounter any problem, and feel free to open new issues!

**Comment by TaviTruman** [comment]
@yatli okay - cool; trying to learn more about LIKQ. I finally got that data! I'll let you know.
