### ISSUE TITLE
.NET Runtime error when using GraphEngine within (Unit) Tests

### ISSUE THREAD

**Issue by nvankaam** [microsoft/GraphEngine#189]
We are running into an issue when we use GraphEngine in unit tests. We have a solution with ~300 unit tests, of which some are long running. These tests run correctly, unless we also include a test project that uses GraphEngine from within tests. In that case the tests stop executing at an arbitrary moment, even if all tests it performed so far succeeded. No error is shown in Visual Studio (but some tests are left unevaluated, even when using "run all"). The moment at which the tests stop running is inconsistent. 

When we run the tests on vsts we observe similar behaviour: The test task fails even if none of the unit tests has failed and the number of tests that are ran varies between each build.

When we look in the windows event log (of a local developer machine) we see the following errors when running the tests:

### 1:
Application: testhost.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFC268FB061 (00007FFC268A0000) with exit code 80131506.

### 2: 
Faulting application name: testhost.exe, version: 15.0.0.0, time stamp: 0xe11610ad
Faulting module name: clr.dll, version: 4.7.2633.0, time stamp: 0x5a4ed8e5
Exception code: 0xc0000005
Fault offset: 0x000000000005b061
Faulting process ID: 0x5790
Faulting application start time: 0x01d3daf8ae64bf87
Faulting application path: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\TESTPLATFORM\testhost.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report ID: b2535b3d-bc8d-459b-9671-93b21c46886e
Faulting package full name: 
Faulting package-relative application ID: 

We found this error code is related to Garbage collection. That would explain the arbitrary moment at which the tests stop executing.

In our environment we have two visual studio solutions. The first solutions contains our code that uses GraphEngine directly, which contains ~100 short unit tests that run fine.

A second larger solution references the dll's produced by the first solution (and also the GraphEngine Nuget package) amongst other Nuget dependencies. This second solution does not call GraphEngine directly, but does use the from tsl generated structs (not accessors) exposed by interfaces in the first solution. This second solution contains ~300 unit- and integration tests, and produces the undesired behaviour when the GraphEngine tests are also included. 

All tests that use GraphEngine are located in the same test project. These tests clear the store using Global.LocalStorage.RemoveCell(x:long) for each cell after each test, and reinitializes a state in GraphEngine before each test. The "crash" happens a few seconds after it finished running all tests from the GraphEngine test project. 

We tried the following, but all show the same behaviour: 
- Using the latest GraphEngine version from Github (With CellId instead of CellID) locally compiled and pushed to our private Nuget repository.
- Using the version from Nuget (1.0.8482)
- Compiling all our project with .net framework version 4.6.1 (We normally use 4.6.2)
- Running the tests on vsts
- Putting <gcConcurrent enabled="false"/> in the app.config of the testproject

Because the issue occurs a few seconds after completing the GraphEngine tests, my feeling is something goes wrong during a teardown of the store. We do currently not call any method to "shutdown" the store (even not SaveStorage). 

- Is there some operation we should perform to "safely" shutdown the store?
- Do you have any suggestions where to look to solve this issue?

**Comment by yatli** [comment]
@nvankaam IIRC we've fixed this issue in `master` -- you've sensed it, it's due to a local memory storage deallocation bug.

**Comment by yatli** [comment]
Searching the commit history with keyword `LocalMemoryStorage`, I've come down to this one:
https://github.com/Microsoft/GraphEngine/commit/4589cca7c768d9e65e4f137ffcd99a5f8b23ec7a

**Comment by nvankaam** [comment]
@yatli Thank you for your response!

I don't think the issue we are running into is solved with that commit. We are using the latest version of graphengine from the master branch (I have validated the change is present by decompiling the GraphEngine.Core dll from our bin directory with ILSpy). We only reverted to the nuget version to see if that would solve this issue. 

I am however able reproduce the problem by taking the "Friends" example from github with a few modifications. Firstly update its GraphEngine dependency to the latest version and its targetframeworkversion to 4.6.1. Next rename CellID to CellId in the main method from the friends example. 

Finaly add two unit test projects called "Test1" and "Test2". The first testproject has a single unit test which just calls the "Main" method from the Friends example (Remove the Console.ReadKey line so it doesn't wait forever). The second testproject has no dependencies to GraphEngine or Friends and just a single unit test with the following code:

```
	[TestClass]
	public class UnitTest1
	{
		[TestMethod]
		public void TestGarbageCollect()
		{
			GC.Collect();
		}
	}
```
  
If you would call GC.Collect() from the testproject that also calls the Friends' main method, the test would succeed. Calling GC.Collect() from a seperate testproject (That runs after the first test project) causes the test runner to crash with the same error in the windows event log as I mentioned in my first post.

Would it help if I upload the solution that reproduces issue to somewhere (Github)?

**Comment by yatli** [comment]
Then it must be a runtime problem. We have internal reports that our current treatment on p/invoke is problematic, and should be switched back to standard p/invoke.

Could you please have a try with `netcore2.0app`? Our `netstandard` version does use standard p/invoke.

**Comment by nvankaam** [comment]
Yes, the issue does not seem to occur when I port the code to `netcoreapp2.0`

**Comment by yatli** [comment]
@nvankaam hang on, we are moving to standard p/invoke on `net451;net46` shortly. will ping you back once it's finished.

**Comment by yatli** [comment]
coming into `master` now; @nvankaam could you give it another try?

**Comment by nvankaam** [comment]
Thank you @yatli ! This has solved the issue, all our tests all pass!
