### ISSUE TITLE
Looks like the DataImporter does not support RDF/XML serialization

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#195]
We are testing the DataImporter and we have a lot of files in RDF/XML file format; looks like only ntriple serialization is currently supported. I am looking for a utility that will convert RDF/XML to ntriple.

**Comment by yatli** [comment]
hi @TaviTruman, I think this might get more complicated than it appears to be. There are many RDF formats out there and we cannot do them one by one. But having a general-purpose XML parser would be definitely very helpful though.

**Comment by TaviTruman** [comment]
@yati As I am still porting my semantic APIS to GE a general purpose W3C parsing suite will be available. I can adapt my parser to load data into GE from legacy 3rd party data providers.
