### ISSUE TITLE
GraphAssembly as a TSL construct

### ISSUE THREAD

**Issue by yatli** [microsoft/GraphEngine#196]
For example,

```
struct Payload
{
    gasm program;
}
```

Then, GraphAssembly can be messaged to remove, persist in storage, or executed locally.

**Comment by TaviTruman** [comment]
@yati that's awesome and very useful.

**Comment by thautwarm** [comment]
Make sense. It indicates that "code is data".

**Comment by yatli** [comment]
Closing this issue now -- won't be implemented until gasm takes shape.
