### ISSUE TITLE
Server Response

### ISSUE THREAD

**Issue by MrCorba** [microsoft/GraphEngine#198]
I've got a small GraphEngine application with the following models:

```C#
[GraphNode]
cell Word
{	
	bool Subject;
	[Index]
	string Description;
	[GraphEdge : Outlinks]
	List<Edge> SynonymList;
}
struct Edge
{
	long Link;
	float Weight;
}
```

I've added a server and want to return a word, with all it's synonyms as words instead of **Edge**. 

I can't create a field with type **Word** in the edge, because it's a **Cell** and not a **Struct/Enum**.  

Then I tried to create new models called **WordResponse** and **EdgeResponse**, with the **EdgeResponse** holding the values of the synonyms:

```C#
struct EdgeRespone
{
	bool Subject;
        long CellId;
        string Description;
	float Weight;
}
```
The downside here was the parsing of all the data to new objects took a long time. I tried creating a simple wrapper C# class, but I couldn't set this in the TSL because the compiler doesn't know these classes. 

I could set all the data I need in the **Edge**, but then it will be a lot of duplication.

Am I missing something and is there an easy way to achieve this? Or is the way with the _ResponseObjects_ the way to go?

Cheers!

**Comment by yatli** [comment]
hi @MrCorba !
What's the signature of your protocol? Are you trying to wrap a list of edges in a response?

**Comment by MrCorba** [comment]
Hey @yatli !

The response chain I'm currently sending consists of the following models:

```C#
protocol Get
{
    type:HTTP;
    request:GetRequest;
    response:GetResponse;
}
Struct GetResponse 
{
	int StatusCode;
	optional WordResponse Result;
	optional string Message;
}
Struct WordResponse
{	
	CellId WordId;
	bool Subject;
	string Description;
	optional List<EdgeResponse> SynonymList;
}
Struct EdgeResponse
{
	CellId WordId;
	string Description;
	float Weight;
}
```

The idea is to get this kind of result: 

```json
{ 
  "description": "synonym",
  "wordId": 123456,
  "subject": "true",
  "synonyms": [
    {
      "wordId": 456789,
      "Description": "equivalent",
      "Weight": 0.9
    } 
  ]
}
```

I can iterate over the graph fairly fast, but as soon as I create a **WordResponse** to return, this takes a lot of time.

**Comment by yatli** [comment]
Ah, a WordNet application isn't it. :D 
I figure it would be better if you write raw json stream in the http handler? Like,

```
protocol Get {
    Type: Http;
    Request: GetRequest;
    Response: Stream; // <--- that
}
```

In this way you can hook up a StreamWriter and dump the results even while you're doing traversal.

**Comment by yatli** [comment]
The core idea is, TSL does an Ok job with default json capabilities, but you can get more flexibility when you bypass it.

**Comment by MrCorba** [comment]
It's a WordNet like idea indeed;)

Mmm, let me try the stream. Thanks for the tip!

**Comment by yatli** [comment]
@MrCorba I’m closing this for now. Feel free to reopen if you’ve got more questions.
