### ISSUE TITLE
Question: PowerShell and GE

### ISSUE THREAD

**Issue by eosfor** [microsoft/GraphEngine#199]
Hello colleagues, i'm trying to play around with GE using PowerShell. Actually I'm trying to make a [module](https://github.com/eosfor/GraphEngineModule) to work with GE using PowerShell.

So far i got a question. I have the following piece of code, which performs kid of initialization.

```csharp
TrinityConfig.LogEchoOnConsole = LogEchoOnConsole;
LoggingConfig.Instance.LogDirectory = LogDirectory;
StorageConfig.Instance.StorageRoot = StorageRoot;

Global.Initialize();

LambdaDSL.SetDialect("MAG", "StartFrom", "VisitNode", "FollowEdge", "Action");
FanoutSearchModule.SetQueryTimeout(-1);

TrinityServer server = new TrinityServer();
server.RegisterCommunicationModule<FanoutSearchModule>();
server.Start();
```

However, when this runs as part of PowerShell module i see some noise on the PowerShell console, like this:

![image](https://user-images.githubusercontent.com/9363027/39705223-6e018194-5216-11e8-8f08-1e7540724cab.png)

What do i do. How can i properly initialize an avoid any output to console? Or control this output?

**Comment by yatli** [comment]
hi @eosfor !
If you have set LogEchoOnConsole but still observe the 'noise' being scattered, you could try to work it around by setting LogLevel to Off.

**Comment by eosfor** [comment]
Hello @yatli,

I've updated the call a bit.

This part passes the parameters from cmdlet to initialization routine and generates verbose output (in yellow)

```csharp
if (!GlobalState.Instance.IsInitialized)
{
    WriteVerbose($"Setting LogDirectory to: {LogDirectory}");
    WriteVerbose($"Setting StorageRoot to: {StorageRoot}");
    WriteVerbose($"Setting LogEchoOnConsole to: {LogEchoOnConsole}");
    WriteVerbose($"Setting LogLevel to: {LogLevel}");

    GlobalState.Instance.Initialize(LogDirectory, StorageRoot, LogEchoOnConsole, LogLevel);
}
```

And this part is initialization  itself

```csharp
public void Initialize(string LogDirectory, string StorageRoot, bool LogEchoOnConsole, Trinity.Diagnostics.LogLevel LogLevel)
{
    if (!_isInitialized )
    {
        TrinityConfig.LogEchoOnConsole = LogEchoOnConsole;
        LoggingConfig.Instance.LogDirectory = LogDirectory;
        LoggingConfig.Instance.LoggingLevel = LogLevel;
        StorageConfig.Instance.StorageRoot = StorageRoot;

        Global.Initialize();

        LambdaDSL.SetDialect("MAG", "StartFrom", "VisitNode", "FollowEdge", "Action");
        FanoutSearchModule.SetQueryTimeout(-1);

        TrinityServer server = new TrinityServer();
        server.RegisterCommunicationModule<FanoutSearchModule>();
        server.Start();

        _isInitialized = true;
    }
}
```

And here is the output.

![image](https://user-images.githubusercontent.com/9363027/39745323-98826020-52af-11e8-8120-037a00a3168b.png)

As you can see it still outputs stuff to a console for some reason.

**Comment by yatli** [comment]
Hmm, I think the options are flushed by initialization. I'll look into it shortly.
@leasunhy got time to take a look?

**Comment by eosfor** [comment]
This is how it is happening

https://www.screencast.com/t/7zS7XjjHD7E

**Comment by yatli** [comment]
Looking into this now.

**Comment by yatli** [comment]
@eosfor could you please pull `master` and try again? That should be a drop-in fix.

**Comment by eosfor** [comment]
Sure @yatli, will do and let you know

**Comment by eosfor** [comment]
@yatli, it works better now

![image](https://user-images.githubusercontent.com/9363027/39918434-178504c0-5519-11e8-814f-d8c015d0bf54.png)

However, there is an output left (marked on a screeshot), generated by this call:

![image](https://user-images.githubusercontent.com/9363027/39918483-42d73ed6-5519-11e8-9684-c936f684b3ae.png)

**Comment by yatli** [comment]
Uh oh, this is probably from the storage composition module. It must be another Console.WriteLine...

Will fix this really soon!

cc @thautwarm

**Comment by yatli** [comment]
@eosfor should be alright now
