### ISSUE TITLE
cross platform build

### ISSUE THREAD

**Issue by ehartford** [microsoft/GraphEngine#2]
I want a build procedure that works cross platform from the command line at the root level of the project.

ie, I want to:

    make && make install

or even something like 

    sudo apt-get install msbuild && msbuild buildall.sln

build procedure should be documented in the README.md.

**Comment by larsgk** [comment]
Maybe a VS Code plugin as well (cross platform)

If not "make && make install" ... at least some common ground like pip or npm ?

**Comment by shaobin** [comment]
The cross platform support and the toolchain are on the way.

**Comment by yatli** [comment]
The typical workflow for GE app development is to reference the GraphEngine.Core nuget package. So once the xplat package is available you'll be able to get the package with a nuget package restore (dotnet restore in the coreclr vocabulary).

And I guess `make install` means to install the package into a local nuget source? :)

**Comment by yatli** [comment]
@larsgk developing GE apps is pretty much like to develop a standard .NET app (nuget is roughly equivalent to pip or npm), except that you'll need to create/edit Trinity Specification Language (TSL) scripts to generate strongly-typed data accessors. 

We definitely need to bring syntax highlighter for TSL to VSCode (just like https://github.com/v-yadli/vim-tsl).

**Comment by ehartford** [comment]
@yatli no I'm not talking about building an app with GraphEngine.Core as a dependency.
I'm talking about building GraphEngine.Core itself...
This is open source right?  I can add new features to it and change it if I want, and rebuild it.

**Comment by yatli** [comment]
@ehartford yeah, sure, but what I mean is that I'm not sure about what should `make install` do when the nuget package is built.

**Comment by yatli** [comment]
@ehartford check this out: https://github.com/Microsoft/GraphEngine/pull/61
