### ISSUE TITLE
Deadlock, do i do something wrong?

### ISSUE THREAD

**Issue by eosfor** [microsoft/GraphEngine#205]
Hello colleagues,

In general i want to do come processing by comparing all nodes to each other and applying some changes to them. This it the piece of code

```csharp

        public void Run (int times)
        {
            foreach (var node in Global.LocalStorage.SimpleNode_Selector())
            {
                //Do something...
                Console.WriteLine(node.Label);
                ProcessNode(node);
            }
        }

        private void ProcessNode (SimpleNode node)
        {
            List<Vector3> vectors = new List<Vector3>();
            foreach (var n in Global.LocalStorage.SimpleNode_Selector())
            {
                if (n.CellId != node.CellId)
                {
                    #region Processing
                    #endregion
                }
            }
        }
```

When the ProcessNode  gets called it simply hangs inside of ```in``` statement. It seems like a deadlock, but i can't figure out what to do and what is the correct way to do such processing. May i ask for an advice, please. Sorry if the question is lame.

**Comment by eosfor** [comment]
Here is what i suddenly got

![image](https://user-images.githubusercontent.com/9363027/40552113-77da027e-6047-11e8-8041-b97427b8224c.png)

May it be because of powershell.exe restrictions?

**Comment by yatli** [comment]
aha, mulit cell lock! Allocate a `LocalTransactionContext` and use it to access multiple cells at the same time.

**Comment by yatli** [comment]
something like:

using(var tx = new LocalTransactionContext())
{
    foreach(var c1 in Global.LocalStorage.YourCell_Selector(tx))
    {
        ....
    }
}

**Comment by eosfor** [comment]
Seems did not work :(

**Comment by yatli** [comment]
@eosfor could you elaborate? Still locked?

**Comment by yatli** [comment]
Closing inactive issue.
