### ISSUE TITLE
Sample and Test GE/SF Server App and Client Apps have errors

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#207]
I'm going to start by lumping these all together as they all seem to be related. We are in the process or going through all of the GE/SF components and API, there is a lot there, and we are running into little things here and there. Right now we are running into lots of "Coded Workflow" gaps in how to build GE/SF Service and Client bits, and what I show here as "**Not authorized to connect**" errors.  We are getting the same errors in the product development builds, so I did not see the need to try to make that code available for review when the stock samples exhibit the exact same problems.

We get these errors using the Trinity.ServiceFabric.SampleApplication and sample Test Clients: (Trinity.ServiceFabric.GraphEngineRemotingClient and Trinity.ServiceFabric.GraphEngineService) 

![image](https://user-images.githubusercontent.com/5692812/41820502-b4af8082-7787-11e8-9d28-1395f6d48355.png)

![image](https://user-images.githubusercontent.com/5692812/41820744-44224760-778b-11e8-967f-91086c66cd3c.png)

"Not authorized to connect" in the "Stateless" example using the **GraphEngineRemotingClient(context)).GetAwaiter().GetResult();** API call.

![image](https://user-images.githubusercontent.com/5692812/41820609-539a5d06-7789-11e8-9d8b-4e31c9c71adc.png)

The "Stateful" version seems to get a bit further along in processing: (See Console IO Log):

![image](https://user-images.githubusercontent.com/5692812/41820647-feeec2f0-7789-11e8-8623-365aafb49e71.png)

![image](https://user-images.githubusercontent.com/5692812/41820652-14239b0a-778a-11e8-9f18-2db46418a1e9.png)

**Comment by yatli** [comment]
Hi @TaviTruman ,

Please start the SF sample app package instead of the service, or the client, directly.

See:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-troubleshoot-local-cluster-setup

**Comment by yatli** [comment]
The package should start both the client and the service at the same time. You'll be able to inspect the status through the ETW logs.

**Comment by TaviTruman** [comment]
@yatli Hello Yatao. Thanks for getting back so quickly; this is a boo-boo on us; we've been using code from a codebase packaged differently, and when we updated we start getting a lot of errors. There is some confusion that stems from the workflow my team learned to build SF App/Services beginning from Service Fabric plugin supplied by Microsoft in VS. With the current GE/SF implementation, our starting base is the **GraphEngineService.cs** file found in the _Trinity.ServiceFabric.Infrastructure library_, so you're starting a bit further downstream in the coded workflow. In the samples you supplied, we just needed to step back and modify our workflow. I had a starting point developed going back to where you and I were working out a few issues; as you cleaned that code up we need to change our process. One thing to note, however, is that if we just stop and start the Trinity.ServiceFabric.SampleApplication it does have an error in two places:  one in the "fabric/System/DnsService:"

![image](https://user-images.githubusercontent.com/5692812/41850048-116b922e-7838-11e8-93ae-bed7546cec78.png)

and the other here: Service fabric:/Trinity.ServiceFabric.SampleApplication/Trinity.ServiceFabric.GraphEngineService

![image](https://user-images.githubusercontent.com/5692812/41850199-8e366d2e-7838-11e8-8d29-b9b705312c20.png)

Unhealthy event: SourceId='Trinity.ServiceFabric.HealthManager', Property='ReportPartitionStatus', HealthState='Warning', ConsiderWarningAsError=false.
Partition 1 has not initialized the chunk table.

The SF Health monitor considers this problem server enough to report "Trinity.ServiceFabric.GraphEngineService" down. 

Other than these items, things are working well.

**Comment by TaviTruman** [comment]
Okay, I stopped and restarted; executed the publish step and again and all is well. The initial problem did persist for 24 hours but now all is well. I am closing this issue. 

![image](https://user-images.githubusercontent.com/5692812/41851019-72375b6c-783b-11e8-9d99-26a5aa07f222.png)
