### ISSUE TITLE
Seeing lots of "Exception Throw" in Trinity.ServiceFabric.Infrastructure

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#208]
![image](https://user-images.githubusercontent.com/5692812/41929424-d181ca8e-792c-11e8-913b-f8729312e9f6.png)

![image](https://user-images.githubusercontent.com/5692812/41929465-fa558130-792c-11e8-84e6-6b482b41f18a.png)

![image](https://user-images.githubusercontent.com/5692812/41929144-239d8e58-792c-11e8-9e1e-06869e975755.png)

![image](https://user-images.githubusercontent.com/5692812/41929207-36d875fa-792c-11e8-8b9d-3b1b61b6ed67.png)

**Comment by TaviTruman** [comment]
@yatli As you can see the "StatefulService" implementation is not stable. This in effects halts my development. I'm actively debugging, tracing and documenting my findings.

**Comment by TaviTruman** [comment]
@yatli Hi Yatao I'm getting mixed results in testing fabric:/Trinity.ServiceFabric.SampleApplication/Trinity.ServiceFabric.GraphEngineService. The problems take place in Trinity.DynamicCluster. 

![image](https://user-images.githubusercontent.com/5692812/41979004-d41a9e6e-79d7-11e8-8a31-bd3bf6244e4d.png)

{
  "Timestamp": "2018-06-27T06:29:41.3649993-07:00",
  "ProviderName": "Microsoft-ServiceFabric",
  "Id": 54424,
  "Message": "Service=fabric:/Trinity.ServiceFabric.SampleApplication/Trinity.ServiceFabric.GraphEngineService InstanceId=-1 SourceId=Trinity.ServiceFabric.HealthManager Property=ReportMemoryCloudStatus HealthState=Error TTL=922337203685477ms SequenceNumber=131745797767340007 Description='MemoryCloud is not healthy' RemoveWhenExpired=False SourceUTCTimestamp=06/27/2018 06:29:36 ",
  "ProcessId": 27692,
  "Level": "Informational",
  "Keywords": "0x4000000000000001",
  "EventName": "HM",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "eventInstanceId": "\"5b61482a-e6e2-4184-9d69-1241568f935c\"",
    "serviceName": "fabric:/Trinity.ServiceFabric.SampleApplication/Trinity.ServiceFabric.GraphEngineService",
    "instanceId": -1,
    "sourceId": "Trinity.ServiceFabric.HealthManager",
    "property": "ReportMemoryCloudStatus",
    "healthState": 3,
    "TTLtimespan": 922337203685477,
    "sequenceNumber": 131745797767340007,
    "description": "MemoryCloud is not healthy",
    "removeWhenExpired": false,
    "sourceUtcTimestamp": "\"\/Date(1530106176734)\/\""
  }
}

At times the service will run for a time without error:

![image](https://user-images.githubusercontent.com/5692812/41978852-86d7e210-79d7-11e8-8aa9-e732df1e70e6.png)

{
  "Timestamp": "2018-06-27T06:29:44.2109599-07:00",
  "ProviderName": "Microsoft-ServiceFabric.Trinity.StatefulService",
  "Id": 1,
  "Message": "[P0-Saint Anna]\tGraph Engine Client .. Ping received!",
  "ProcessId": 40892,
  "Level": "Informational",
  "Keywords": "0x0000F00000000001",
  "EventName": "GraphEngineLogInfo",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "message": "[P0-Saint Anna]\tGraph Engine Client .. Ping received!"
  }
}
With the mixture of errors and health warnings and key parts of the GE/SF unavailable I am not certain of what I'm looking at and confidence is low right. I will continue to test try to get to the bottom of what's going on here.

**Comment by TaviTruman** [comment]
I've been testing and tracing still can't get consistent results here; sometimes the GE/SF cluster is stable and reports all partitions and nodes and healthy but most of the time I get an error. The whole thing becomes even more of a mess when I start testing for failover and redundancy. I could really use some feedback, input advice here.

**Comment by yatli** [comment]
Hey Tavi,

I’m on business trip @HQ; will ping you when I’ve got back.

**Comment by TaviTruman** [comment]
@yatli Thank you Yatao! Hope you have a great trip.

**Comment by TaviTruman** [comment]
@yatli Hello Yatao. Do you think you might have some time to address these issues; our development with GE and Service Fabric is slowing and increasing more problematic.

**Comment by TaviTruman** [comment]
@yatli Hello Yatao. I've been doing a lot of testing and the results are better as you can see in the screen short below. After 2 months of digging into the code and tracing everything I understand what's going on now. Part of the problem was that I needed to make some changes on to my local SF configuration. In testing the Storage module I had to include my setup and not the default in the code. I'm going to close this because I understand the codebase and sample very well now. As the GE/SF is mostly undocumented and great many things may seem and are difficult to follow. You've done a masterful job with the GE to SF integration but one must be familiar, comfortable with SF and GE concepts to really go to town!

the Red in the display does not give one a warm and fussy feeling but the GE/SF integration is working. I think more work is required in the way of GE Health management in the SF and we need security. Now that I'm much more familiar and comfortable with both GE and SF I can add security myself and spruce up the health management.

![image](https://user-images.githubusercontent.com/5692812/43558427-5130f090-95be-11e8-8c55-1328d2223c8e.png)

![image](https://user-images.githubusercontent.com/5692812/43558407-340a7234-95be-11e8-8634-a63e210da9f8.png)
