### ISSUE TITLE
GE Client Stalls running Multiple instance of GE Client

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#210]
1. Start the supplied Trinity.Client.TestServer
2. Start the supplied Trinity.Client.TestClien and all is right with the world
3. Start another instance of the TestClient and the first TestClient stalls while the second TestClient picks up where the first TestClient stalled
4. Note: that the TestServer has registered two TestClient instances
5. When I start yet another TestClient all Client instances stop responding
There more bad things happen when you try to stop the clients and restart them

![image](https://user-images.githubusercontent.com/5692812/42230824-cb084fa8-7e9e-11e8-8577-786d36c95adf.png)

**Comment by TaviTruman** [comment]
This is becoming a very urgent problem!

**Comment by yatli** [comment]
@TaviTruman the test app demonstrates how to differentiate multiple clients.

Take a look at the test server code here:

```C#
var client = cmod.Clients.FirstOrDefault();
```

It only probes the first client in the collection.
If you want all of the clients to be probed, iterate over `cmod.Clients`.

**Comment by TaviTruman** [comment]
@yatai thanks 🙏 Yatao. I did finally figure that out. Thanks for circling back.
