### ISSUE TITLE
Error: MemoryTrunk failed to expand on Ubuntu after (re)loading storage

### ISSUE THREAD

**Issue by nvankaam** [microsoft/GraphEngine#212]
I am trying to deploy services that use GraphEngine inside Ubuntu docker containers, but I am getting the following error:
```
"CommittedMemoryExpand: MemoryTrunk 110 failed to expand.
[ ERROR   ] CellAlloc: MemoryTrunk 110 is out of Memory.
``` 
The `110` can be any number between 0 and 255.

After some experiments I observe no relation between this error and the cellid generation. I have tried bothrandom hashing and just sequential numbers, as suggested in https://github.com/Microsoft/GraphEngine/issues/123, so I think this issue is different.

I am however able to consistently reproduce the issue outside docker on an Ubuntu virtual machine. The issue occurs when I save a store, restart the application, reload the store, and start inserting again. 

I can reproduce the issue using the following small application, using the lastest version of the master branch of this repository:

Program.cs:
```
 public class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Loading storage");
			Global.LocalStorage.LoadStorage();
			var count = Global.LocalStorage.GenericCellAccessor_Selector().Count();
			Console.WriteLine($"Storage loaded. {count} in store.");
			Console.WriteLine($"How many entities would you like to insert?");
			int intTemp = Convert.ToInt32(Console.ReadLine());
			Console.WriteLine($"Generating {intTemp} entities");
			//Generate some sample data
			for (var i = 0;i<intTemp; i++)
			{
				Global.LocalStorage.SaveSampleEntity(RandomEntity());
			}
			count = Global.LocalStorage.GenericCellAccessor_Selector().Count();
			Console.WriteLine($"Entities generated. {count} in store");

			Global.LocalStorage.SaveStorage();
			Console.WriteLine($"Saved storage");
		}

		private static SampleEntity RandomEntity()
		{
			return new SampleEntity()
			{
				CellId = CellIdFactory.NewCellId(),
				name = RandomString(16)
			};
		}


		private static Random random = new Random();
		public static string RandomString(int length)
		{
			const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
			return new string(Enumerable.Repeat(chars, length)
			  .Select(s => s[random.Next(s.Length)]).ToArray());
		}
	}
```

Model.tsl:
```
cell struct SampleEntity {
	String name;
}
```

I start the application with the command `dotnet TrinityDemo.dll` (My project is called TrinityDemo).

When I initially start the program without an existing store and let it create 10 000 000 sample entities it will do so correctly and save the storage. However when I then start the application again and try to insert 1000 more entities, I get the out of memory exceptions. Meanwhile the VM has plenty of memory left and hasn't even touched the swap file yet.

When I start the same application on the same VM and just insert 100 000 000  (10 times more than previous) entities in a single go without loading the storage, the error does not occur. I therefore don't think the amount of available memory on the VM is related to the problem. The error also does not occur when I perform the same steps on a windows machine (Also using dotnet core). I would therefore suspect the issue lies somewhere in the native library.

Please let met know if there is any more information I can provide to help!

**Comment by nvankaam** [comment]
Some additional info:

I am building the code with the `dotnet publish` command on a windows 10 home edition machine. Adding `<RuntimeIdentifier>ubuntu.16.04-x64</RuntimeIdentifier>` to the csproject before buiding does not seem to make a difference.

**Comment by nvankaam** [comment]
Some additional info 2:

If I build the project on Ubuntu instead of Windows I get the following error when inserting 10 million entities (even without performing a save or load):

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Model.SampleEntity_Accessor.AllocIterativeAccessor(CellInfo info, LocalTransactionContext tx) in /home/nvankaam/Documents/dotnet/TrinityDemo/Model/obj/Release/netcoreapp2.0/GeneratedCode/Cells/SampleEntity.cs:line 788
   at Model.GenericCellOperations.<EnumerateGenericCellAccessors>d__10.MoveNext() in /home/nvankaam/Documents/dotnet/TrinityDemo/Model/obj/Release/netcoreapp2.0/GeneratedCode/Lib/GenericCell.cs:line 233
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at TrinityDemo.Program.Main(String[] args) in /home/nvankaam/Documents/dotnet/TrinityDemo/TrinityDemo/Program.cs:line 21
Aborted (core dumped)
```

**Comment by yatli** [comment]
hi @nvankaam ! let me try to reproduce the problem on a VM. Looks like the storage's got "read-only-ish" after a restart? 10M is not a big number and the default configuration should handle it pretty easily.

**Comment by nvankaam** [comment]
Did you get a chance to reproduce the issue yet?

Please let me know if there is anything I can do to help fixing the issue! Getting the deployment to work within a linux (Ubuntu) container would be very helpful to me :)

**Comment by yatli** [comment]
@nvankaam just about to report back!
no, no repro -- tried on WSL and a VM

**Comment by yatli** [comment]
You mentioned container.. I did crash Trinity once in a WindowsServer 2016 Nano container environment -- did you try with a bare-metal machine?

**Comment by nvankaam** [comment]
@yatli I have not tried on a bare metal machine. I have tried in an Ubuntu 16.04 container (with docker on Hyper-V), and Ubuntu 16.04 virtual machine on virtual box.

I will give WSL a try now

**Comment by nvankaam** [comment]
I am also getting the errors in WSL. My windows is running on bare metal.

**Comment by yatli** [comment]
I guess my test entities are too small (4 bytes each) -- how about your `SampleEntity`?
Edit: it could be less related to the number of entities, but the total size

**Comment by nvankaam** [comment]
The code I used to generate the examples is in the first post. My SampleEntity has 1 string property, and I fill each entity with a random string of 16 characters.

**Comment by yatli** [comment]
let me try that instead.

**Comment by yatli** [comment]
@nvankaam the problem is reproduced! I tried with your sample, and also observed OOM when I expand the cell layout in my repro to this:

```
cell TC
{
    byte[36] data; // 16char string takes 36 bytes
}
```

Initially it was:
```
cell TC
{
    int data; // 4 bytes
}
```

So that results in the difference in total size (approx. 1.34MB vs 149KB per trunk).

**Comment by nvankaam** [comment]
Not sure if still relevant now: I have tried with smaller entities (String length 1 instead of 16), and observe the error from ~60 million entities instead of 10 million.

**Comment by yatli** [comment]
yeah, it's related to the total size of the entities -- probably capped at 1MB due to some misconfiguration.
Investigating.

**Comment by yatli** [comment]
problem identified. Linux requires the buffer to be aligned to system page when committing memory -- overlooked this one back then..

a fix is on the way.

**Comment by yatli** [comment]
@nvankaam pushed a new version to master -- please let me know whether the patch fixes the problem.

**Comment by nvankaam** [comment]
@yatli I am still getting the same error after pulling the latest version.

I am using the nuget package registered on the local graphengine nuget repository, created by the build.ps1 under tools. I do notice that the "libTrinity.so" file in the nuget package has an old timestamp (from april this year), while the "Trinity.dll" of the windows runtime has an updated timestamp.

Is the libTrinity.so also updated when I compile the code on a windows machine? Or has nothing changed in the native library?

**Comment by yatli** [comment]
ah, forgot to mention, libTrinity.so is simply copied over from lib/libTrinity.so and not updated in a Windows build.

**Comment by yatli** [comment]
also, you have to make sure the stale package is removed from ~/.nuget/packages/graphengine.core

**Comment by yatli** [comment]
let me update the native binaries on `master` branch :)

**Comment by nvankaam** [comment]
Alright, thanks! That saves me setting up the dependencies on WSL.

**Comment by yatli** [comment]
Done, you should be able to build a complete package from Windows now.

**Comment by nvankaam** [comment]
Thanks! The issue is no longer occuring in the sample project (Neither on WSL or on an Ubuntu VM), so I think the fix solved it! 

I will need some time to get the docker container back up and running, but I will give an update when I know the results :)
