### ISSUE TITLE
"ProviderName": "Microsoft-ServiceFabric.Trinity.StatefulService",AsyncWithResponse remote handler failed.

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#214]
I'm getting this error when trying to use the StatefulService via GE/SF integration

![image](https://user-images.githubusercontent.com/5692812/43682260-5432681a-9824-11e8-9648-ef340a0a6fd9.png)

**Comment by yatli** [comment]
Looks like the replicator is failing -- the task will retry forever.
How many nodes are in the cluster? How many partitions? Could you please show the config file?

**Comment by TaviTruman** [comment]
I am running in a 5 node cluster. I'll upload the config files

<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ApplicationTypeName="Trinity.ServiceFabric.SampleApplicationType" ApplicationTypeVersion="1.0.0" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <Parameters>
    <Parameter Name="Trinity.ServiceFabric.GraphEngineRemotingClient_InstanceCount" DefaultValue="-1" />
    <Parameter Name="Trinity.ServiceFabric.GraphEngineService_MinReplicaSetSize" DefaultValue="3" />
    <Parameter Name="Trinity.ServiceFabric.GraphEngineService_PartitionCount" DefaultValue="1" />
    <Parameter Name="Trinity.ServiceFabric.GraphEngineService_TargetReplicaSetSize" DefaultValue="3" />
  </Parameters>
  
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="Trinity.ServiceFabric.GraphEngineRemotingClientPkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides />
  </ServiceManifestImport>
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="Trinity.ServiceFabric.GraphEngineServicePkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides />
  </ServiceManifestImport>
  <DefaultServices>
    
    <Service Name="Trinity.ServiceFabric.GraphEngineRemotingClient" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="Trinity.ServiceFabric.GraphEngineRemotingClientType" InstanceCount="[Trinity.ServiceFabric.GraphEngineRemotingClient_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
    <Service Name="Trinity.ServiceFabric.GraphEngineService" ServicePackageActivationMode="ExclusiveProcess">
      <StatefulService ServiceTypeName="Trinity.ServiceFabric.GraphEngineServiceType" TargetReplicaSetSize="[Trinity.ServiceFabric.GraphEngineService_TargetReplicaSetSize]" MinReplicaSetSize="[Trinity.ServiceFabric.GraphEngineService_MinReplicaSetSize]">
        <UniformInt64Partition PartitionCount="[Trinity.ServiceFabric.GraphEngineService_PartitionCount]" LowKey="-9223372036854775808" HighKey="9223372036854775807" />
      </StatefulService>
    </Service>
  </DefaultServices>
</ApplicationManifest>

**Comment by TaviTruman** [comment]
Code stalls here for about 5 minutes

![image](https://user-images.githubusercontent.com/5692812/43703319-4c74a8e8-9911-11e8-9a60-4e0ef277a7c0.png)

**Comment by TaviTruman** [comment]
![image](https://user-images.githubusercontent.com/5692812/43703404-914fd942-9911-11e8-89fa-40c15e7f7d92.png)

**Comment by TaviTruman** [comment]
Here's the node configuration

![image](https://user-images.githubusercontent.com/5692812/43703542-e0ae2f7a-9911-11e8-88e1-1078c7201412.png)

**Comment by TaviTruman** [comment]
Here is the configuration file for the Trinity Configuration (GraphEngineService):

[GraphEngineService Trinity Config File.txt](https://github.com/Microsoft/GraphEngine/files/2261767/GraphEngineService.Trinity.Config.File.txt)

**Comment by yatli** [comment]
Well... in your config file there's `Trinity.DynamicCluster MinimumReplica="4"` -- the replicator is complaining about not having enough replicas

**Comment by TaviTruman** [comment]
Yes but sometimes this works and most times it fails. As i am testing the code as is i have not made any changes to config files or the samples. I can get the sample code as is to work reliably.

**Comment by TaviTruman** [comment]
@yatli I'm confused. Here is the project structure for the GraphEngineService; please note that there's configuration files in the Data section of the configuration:

![image](https://user-images.githubusercontent.com/5692812/43718233-dccdc9b0-993e-11e8-81aa-c930c0c95d17.png)

![image](https://user-images.githubusercontent.com/5692812/43718736-60b2bdf2-9940-11e8-8b1f-9b619531c661.png)

In the Code Section in the settings.xml files the trinity.xml file is referenced; I am including both files for your review. In the trinity.xml file the "replica count is set to the value 2". 

"<Trinity.DynamicCluster MinimumReplica="2" ReplicationMode="Mirroring"/>"

The second file, not referenced in the settingsx.ml file, has a replica count of  "4."

Taken the "trinity_large_memory.xml" file:
"<Trinity.DynamicCluster MinimumReplica="4" ReplicationMode="Mirroring"/>"

**_Note: I made the mistake of sending you bad information. I believe that the replica count value of "2" is being used, not "4"._**

This made sense to me as we are limited to 5 nodes in local service fabric run-mode.

I have noticed replica count on my machine has gotten high as 8, with no errors, but now it never gets higher than 3 and in the ETW log I can see that it never readies the last replica.

**Comment by TaviTruman** [comment]
@yatli Hello Yatao. I have fixed the Replica problem - it was due to a misconfiguration of the Partition and Replica Target and Min count values. I never thought that I would need to adjust them as I assumed the sample would work as is coded. You can see here that my Partitions and Replicas are all reporting healthy status but we are back to the original problem that there is something wrong with the "MemoryCloud" readiness. 

![image](https://user-images.githubusercontent.com/5692812/43734315-2a24b84a-996c-11e8-8733-7ae23202ae69.png)

Service fabric:/Trinity.ServiceFabric.SampleApplication/Trinity.ServiceFabric.GraphEngineService 
ACTIONS 
Essentials 

Details 

Manifest 

<ServiceManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ManifestId="96669a46-1fb2-4e92-8583-15dba444bef5" Name="Trinity.ServiceFabric.GraphEngineServicePkg" Version="1.0.0" xmlns="http://schemas.microsoft.com/2011/01/fabric">

  <ServiceTypes>

    <StatefulServiceType ServiceTypeName="Trinity.ServiceFabric.GraphEngineServiceType" HasPersistedState="true" />

  </ServiceTypes>

  <CodePackage Name="Code" Version="1.0.0">

    <EntryPoint>

      <ExeHost>

        <Program>Trinity.ServiceFabric.GraphEngineService.exe</Program>

      </ExeHost>

    </EntryPoint>

  </CodePackage>

  <ConfigPackage Name="Config" Version="1.0.0" />

  <DataPackage Name="Data" Version="1.0.0" />

  <Resources>

    <Endpoints>

      <Endpoint Name="ReplicatorEndpoint" />

      <Endpoint Name="TrinityHttpEndpoint" />

      <Endpoint Name="TrinityProtocolEndpoint" />

      <Endpoint Name="TrinityServiceFabricRemotingEndpoint" />

    </Endpoints>

  </Resources>

</ServiceManifest>

![image](https://user-images.githubusercontent.com/5692812/43734463-b36cdfec-996c-11e8-9e9d-386e09201d6c.png)

![image](https://user-images.githubusercontent.com/5692812/43734289-18a5d748-996c-11e8-8946-8a3181dd94a1.png)

This is what I see in the ETW log:
{
  "Timestamp": "2018-08-06T11:42:36.6075161-07:00",
  "ProviderName": "Microsoft-ServiceFabric.Trinity.StatefulService",
  "Id": 3,
  "Message": "[P0-Letha]\t",
  "ProcessId": 52120,
  "Level": "Error",
  "Keywords": "0x0000F00000000001",
  "EventName": "GraphEngineLogErr",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "message": "[P0-Letha]\t"
  }
}

{
  "Timestamp": "2018-08-06T11:42:36.6075044-07:00",
  "ProviderName": "Microsoft-ServiceFabric.Trinity.StatefulService",
  "Id": 3,
  "Message": "[P0-Letha]\t   at Trinity.DynamicCluster.DynamicClusterBase._GetChunks_ResponseHandler(AsynReqRspArgs args)
       at Trinity.Network.Messaging.AsynReqRspArgs.MessageProcessProc()",
  "ProcessId": 52120,
  "Level": "Error",
  "Keywords": "0x0000F00000000001",
  "EventName": "GraphEngineLogErr",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "message": "[P0-Letha]\t   at Trinity.DynamicCluster.DynamicClusterBase._GetChunks_ResponseHandler(AsynReqRspArgs args)
         at Trinity.Network.Messaging.AsynReqRspArgs.MessageProcessProc()"
  }
}

**This seems to be the problem!**

{
  "Timestamp": "2018-08-06T11:42:36.6075018-07:00",
  "ProviderName": "Microsoft-ServiceFabric.Trinity.StatefulService",
  "Id": 3,
  "Message": "[P0-Letha]\tAsync task completion token not found while processing a AsyncWithResponse message.",
  "ProcessId": 52120,
  "Level": "Error",
  "Keywords": "0x0000F00000000001",
  "EventName": "GraphEngineLogErr",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "message": "[P0-Letha]\tAsync task completion token not found while processing a AsyncWithResponse message."
  }
}

{
  "Timestamp": "2018-08-06T11:51:41.1242098-07:00",
  "ProviderName": "Microsoft-ServiceFabric",
  "Id": 54424,
  "Message": "Service=fabric:/Trinity.ServiceFabric.SampleApplication/Trinity.ServiceFabric.GraphEngineService InstanceId=-1 SourceId=Trinity.ServiceFabric.HealthManager Property=ReportMemoryCloudStatus HealthState=Error TTL=922337203685477ms SequenceNumber=131780550912201627 Description='MemoryCloud is not healthy' RemoveWhenExpired=False SourceUTCTimestamp=08/06/2018 11:51:31 ",
  "ProcessId": 30404,
  "Level": "Informational",
  "Keywords": "0x4000000000000001",
  "EventName": "HM",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "eventInstanceId": "\"a85556b4-d122-4096-a1f7-027089a15a48\"",
    "serviceName": "fabric:/Trinity.ServiceFabric.SampleApplication/Trinity.ServiceFabric.GraphEngineService",
    "instanceId": -1,
    "sourceId": "Trinity.ServiceFabric.HealthManager",
    "property": "ReportMemoryCloudStatus",
    "healthState": 3,
    "TTLtimespan": 922337203685477,
    "sequenceNumber": 131780550912201627,
    "description": "MemoryCloud is not healthy",
    "removeWhenExpired": false,
    "sourceUtcTimestamp": "\"\/Date(1533581491220)\/\""
  }
}

**Comment by TaviTruman** [comment]
@yatli Hello Yatao. Okay I've been able to configure the GE and Service Fabric so that SF Explorer shows all is well as you can see in the screen shot below. This was very frustrating; I've learned more about SF Capacity Planning and about the GE Integration. I'm sure I have more to learn!
![Uploading image.png…]


![image](https://user-images.githubusercontent.com/5692812/43738952-40377992-997b-11e8-89a7-26dfac28b9df.png)

Please take a look at this as the in the ETW log the GE is generating an exception but is not server enough to disrupt the SF Cluster.

{
  "Timestamp": "2018-08-06T13:28:34.9796683-07:00",
  "ProviderName": "Microsoft-ServiceFabric.Trinity.StatefulService",
  "Id": 3,
  "Message": "[P0-Eric the Red]\tTaskExecutionProc: task 43db332b-beb4-4caa-9fdb-b1a3505d0e7e failed with exception: System.Exception: AsyncWithResponse remote handler failed.
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Trinity.DynamicCluster.Tasks.ReplicatorTask.<DoReplication>d__13.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Trinity.DynamicCluster.Tasks.ReplicatorTask.<Execute>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Trinity.DynamicCluster.Tasks.ChainedTasks.<Execute>d__8.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Trinity.DynamicCluster.Tasks.Executor.<TaskExecutionProc>d__6.MoveNext()",
  "ProcessId": 24468,
  "Level": "Error",
  "Keywords": "0x0000F00000000001",
  "EventName": "GraphEngineLogErr",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "message": "[P0-Eric the Red]\tTaskExecutionProc: task 43db332b-beb4-4caa-9fdb-b1a3505d0e7e failed with exception: System.Exception: AsyncWithResponse remote handler failed.
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Trinity.DynamicCluster.Tasks.ReplicatorTask.<DoReplication>d__13.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Trinity.DynamicCluster.Tasks.ReplicatorTask.<Execute>d__11.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Trinity.DynamicCluster.Tasks.ChainedTasks.<Execute>d__8.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Trinity.DynamicCluster.Tasks.Executor.<TaskExecutionProc>d__6.MoveNext()"
  }
}

I have a lot more testing to do so it is too soon to know if this exception will result in other problems.

Tavi
