### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [microsoft/GraphEngine#217]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
* [MemoryTrunk::DisposeLargeObjects](https://github.com/Microsoft/GraphEngine/blob/d7de405d6d9c7ae2c7192db7dcd1d5588ff37ef5/src/Trinity.C/src/Storage/MemoryTrunk/MemoryTrunk.LO.cpp#L79 "MemoryTrunk::DisposeLargeObjects function")
* [MemoryTrunk::DumpAddressTable](https://github.com/Microsoft/GraphEngine/blob/45ea2d4999aba62eb96263154e91560c16568753/src/Trinity.C/src/Storage/MemoryTrunk/MemoryTrunk.AddressTable.cpp#L72 "MemoryTrunk::DumpAddressTable function")

**Comment by yatli** [comment]
hi @elfring!

I'm glad someone is digging our codebase, and welcome :)

You're right about the delete style. Some of these checks are necessary because they nullify the pointer if freed, though.

**Comment by elfring** [comment]
>Some of these checks are necessary because they nullify the pointer if freed, though.

* I find these pointer checks still redundant.
* Would you like to increase the usage of smart pointers also for this software instead?

**Comment by yatli** [comment]
I'm still not sure if it's safe to make the change in our codebase. Even in the implementation of a std::unique_ptr, it is necessary to null-check before calling the deleter. A custom allocator/deleter might not be able to do this for us.

Yes, unique_ptr is good. But it won't go as deep into our system into the memory storage.

Closing this issue now, feel free to add more comments.

**Comment by elfring** [comment]
I am curious to know where your uncertainty comes from in this use case.
:crystal_ball: Should any technical properties become clearer?
