### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [microsoft/GraphEngine#218]
Would you like to [wrap any pointer data members](https://github.com/Microsoft/GraphEngine/blob/45ea2d4999aba62eb96263154e91560c16568753/src/Trinity.C/src/Storage/MemoryTrunk/MemoryTrunk.cpp#L35 "Update candidate: MemoryTrunk class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by yatli** [comment]
You can basically assume MemoryTrunk is nothrow. Everything runs on error codes.
We will not flip the switch unless it's sufficiently tested.

**Comment by elfring** [comment]
* Is the mentioned assumption questionable?
* Will you ever care to [fix exception safety concerns with smart pointers](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#rsmart-smart-pointers "Recommendations for the usage of smart pointers")?
