### ISSUE TITLE
Build failure under the x64 setting

### ISSUE THREAD

**Issue by LiangHe-MS** [microsoft/GraphEngine#236]
Settings:
- Visual studio 2017;
- A unified project including a TSL file and C# code;
- Use locally built Graph Engine packages and the VS extension is not installed;
- Tested Target framework: .NET Framework 4.6.1;
- 'Prefer 32-bit' option is off;
- Platform: x64.

Compile error:
> 'A Graph Engine project cannot be built with Prefer32Bit option enabled. Please uncheck the toggle in project properties page, or edit the project file.'

It works fine if the 'Platform' option is set as 'Any CPU'.

**Comment by yatli** [comment]
Thanks Liang! I'm on this.

**Comment by yatli** [comment]
@LiangHe-MS could you please pull `master` and try the latest version? We can reopen this issue if it still doesn't work

**Comment by LiangHe-MS** [comment]
@yatli I have tried the latest version of `master`, it works well if I install `Windows SDK 8.1`. Is `Windows SDK 8.1` necessary for the building? If it is absent, there will be some errors like:
```
"D:\graphengine\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\graphengine\build\src\Trinity.VSExtension\BUILD_Trinity.VSExtension.vcxproj" (default target) (28) ->(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
[D:\graphengine\src\Trinity.VSExtension\Trinity.TSL.ManagedWrapper\Trinity.TSL.ManagedWrapper.vcxproj] [D:\graphengine\build\src\Trinity.VSExtension\BUILD_Trinity.VSExtension.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
[D:\graphengine\src\Trinity.VSExtension\Trinity.TSL.ManagedWrapper\Trinity.TSL.ManagedWrapper.vcxproj] [D:\graphengine\build\src\Trinity.VSExtension\BUILD_Trinity.VSExtension.vcxproj]
```
Here is the message related to the SDK versions during building:
`- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.14393`

**Comment by yatli** [comment]
hmmm, I’ll try it with a fresh vm.
It builds fine on ci server, no win8.1sdk installed.

Nevertheless I think we should go back to target Win8.1– the current builds won’t even run on Win7.

**Comment by BenDerPan** [comment]
I also meet the problem: need Win SDK8.1 to build the vsextension, I fixed it by select the SDK from VS2017  to WinSDK 10.0.15063.0, but I have new problem: #240
