### ISSUE TITLE
Can write_ahead_log be configured?

### ISSUE THREAD

**Issue by TCGOGOGO** [microsoft/GraphEngine#241]
In some cases, we do not want server keep updating log file in write_ahead_log

**Comment by yatli** [comment]
hi,

WAL won't be updated unless you choose to use the logging flags.

**Comment by TCGOGOGO** [comment]
> hi,
> 
> WAL won't be updated unless you choose to use the logging flags.

Hi yatli, thanks for your reply.

How can I close the logging flags?  "TrinityConfig.LogToFile = false;" this seems useless.

**Comment by yatli** [comment]
`TrinityConfig.LogToFile` controls diagnostic log messages that would be echoed on console and written to the text file. WAL is not for diagnostic messages but for durable key/value operations -- which one do you want?

**Comment by TCGOGOGO** [comment]
> `TrinityConfig.LogToFile` controls diagnostic log messages that would be echoed on console and written to the text file. WAL is not for diagnostic messages but for durable key/value operations -- which one do you want?

Thanks for your explanation, I want to close WAL, could you please tell me how to do.

**Comment by yatli** [comment]
@TCGOGOGO if you don't use the logging interfaces, the operations would not be logged (for example, plain `SaveCell`, `LoadCell` etc.

Do you mean the creation of WAL files? Currently it's not configurable, and the file will always be created.

**Comment by TCGOGOGO** [comment]
> @TCGOGOGO if you don't use the logging interfaces, the operations would not be logged (for example, plain `SaveCell`, `LoadCell` etc.
> 
> Do you mean the creation of WAL files? Currently it's not configurable, and the file will always be created.

Thx, got it.
