### ISSUE TITLE
Can I import a tsl file into another tsl file?

### ISSUE THREAD

**Issue by BenDerPan** [microsoft/GraphEngine#244]
Can I import a tsl file into another tsl file? I notice there is a include keyword. I want to define data models in different tsl files, and import in when i need it

**Comment by TaviTruman** [comment]
Hey @BenDerPan I use the include keyword to facilitate modularity and separation of concerns during the TSL data modeling phase; if your TSL file gets very large I use the include keyword as a divide and conquer strategy. If you are look at the JIT TSL file inclusion, then you are talking about Schema Expansion/Evolution and you can do that using the GE Storage Composition API; I've been using it for a few months now.

**Comment by BenDerPan** [comment]
@TaviTruman  Hi, I can't find `Modules/GraphEngine.Jit` now, my situation is : 
1. I defined something in a.tsl, for example: struct A{};
2. Now I want to use struct A in b.tsl, how can I import struct A into b.tsl;
thanks!

**Comment by TaviTruman** [comment]
@BenDerPan I think my use of jargon gave you the wrong impression; in my previous post I mention "JIT TSL"; this is said to mean "Just In Time TSL" file inclusion and not compile time. There is no GraphEngine.Jit project. 

The TSL "include" keywords is purposed to facilitate compile time  inclusion  of other external TSL language productions outside of the immediate file where the "include" keyword  is used.  

See: https://www.graphengine.io/docs/manual/TSL/tsl-basics.html

here's an example:

![image](https://user-images.githubusercontent.com/5692812/48996240-3669d680-f100-11e8-9d39-38fbf85a2880.png)


**1st TSL file:** _StructA.tsl_

enum StartUpCommandWords
{
	StartUp,
	Shutdown,
	Restart,
	Resume
}

struct APIStartUpParams
{
	DateTime activeDateTime;
	Guid trasnactionKey;
	List<StartUpCommandWords> commandKeyWords;
}

cell MyCell
{
    APIStartUpParams ServerParameters;
    List<CellId> ServerMetadataInfoSets;
}

![image](https://user-images.githubusercontent.com/5692812/48996268-539ea500-f100-11e8-87ae-4a20eea2ee7a.png)


**2nd TSL file:** _StructB.tsl_

TrinitySettings
{
	RootNamespace: sample.tslexample.foryou;
}

**include StructA.tsl;**

struct StructMixIn
{
	APIStartUpParams ServerCommandData;
	long StartUpId;
	sbyte ServerVersikonCode;	
}

cell struct NodeHeader
{
	List<CellId>listOfObjects;
}

**Comment by BenDerPan** [comment]
@TaviTruman sorry, I misunderstood, I thought GraphEngine.JIT is an implementation of Java,  I search JIT in issues, and got this:
![image](https://user-images.githubusercontent.com/10903567/48997221-2c8cb580-f18a-11e8-99ac-f7ae0e9c763c.png)

#### thank you for your great help. :)
