### ISSUE TITLE
Memory leak here?

### ISSUE THREAD

**Issue by huoyao** [microsoft/GraphEngine#246]
Should we have to free the buf here, otherwise we will have a memory leak here?
https://github.com/Microsoft/GraphEngine/blob/3a83cba54f5d3d9b2cb1e6cf34670679a9dffcce/src/Trinity.Core/Network/Client/SynClient.Message.cs#L139
This **buf** will not be free if we recieved **TrinityErrorCode.E_NETWORK_RECV_FAILURE**

But, We allocate the buf in https://github.com/Microsoft/GraphEngine/blob/3045175cb39d4a439fae8bb1fbb060b030ee753b/src/Trinity.C/src/Network/Network.cpp#L480

**Comment by yatli** [comment]
hey @huoyao thanks for letting us know! I've taken a look, and yes you're right, that's a leak.
