### ISSUE TITLE
Seems we remove the first 4 byte of message length data for LocalSendMessage?

### ISSUE THREAD

**Issue by huoyao** [microsoft/GraphEngine#247]
https://github.com/Microsoft/GraphEngine/blob/3a83cba54f5d3d9b2cb1e6cf34670679a9dffcce/src/Trinity.Core/Storage/LocalMemoryStorage/LocalMemoryStorage.Message.cs#L36

Here, we send the buf to native codes, but the buf has a 8 byte header with the first 4 byte **message length** data.
Shoule we remove the first 4 byte **message length** data?

Because in
https://github.com/Microsoft/GraphEngine/blob/3a83cba54f5d3d9b2cb1e6cf34670679a9dffcce/src/Trinity.C/src/Events/Events.cpp#L423
Here, "**\*(uint16_t*)message->buf**" seems get 2 bytes of the message length. But, we supporse want to get the message type index here.

**Comment by yatli** [comment]
hi huoyao,

nope, the length header is always invisible to a handler. Notice the length is populated to MessageBuff.Length, not the head of MessageBuf.Buffer.

If sent remotely, the bytes transferred on-wire would be [Length] + [Buffer].

**Comment by yatli** [comment]
closing this issue now;
