### ISSUE TITLE
Global.LocalStorage.SaveInfo(Info)  error

### ISSUE THREAD

**Issue by simple221** [microsoft/GraphEngine#260]
1、 storage.SendMessage(bufferPtr, msg.Length + TrinityProtocol.MsgHeader, out response);  出现{"Network errors occur."}  
2、 return storage.SaveCell(cellId, tmpcell, (ushort)CellType.VulInfo) == TrinityErrorCode.E_SUCCESS;出现
 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。

**Comment by yatli** [comment]
investigating.

**Comment by yatli** [comment]
a fix is devised. testing.

**Comment by yatli** [comment]
@simple221 the patch is coming into master. closing the issue now but feel free to reopen if you still encounters a problem.

**Comment by simple221** [comment]
I don't know why.my colleague used it ok.but on my computer has wrong.

**Comment by simple221** [comment]
> @simple221 the patch is coming into master. closing the issue now but feel free to reopen if you still encounters a problem.

 storage.SendMessage()引发了异常: Trinity.Core.dll 中的“System.IO.IOException”(“Local message handler throws an exception.”)

**Comment by simple221** [comment]
It's OK now .Cause I'm not coding properly leaded to the service to be disconnected.
