### ISSUE TITLE
Span & ReadOnlyMemory

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/GraphEngine#262]
Please concider using .net core Span<> and ReadOnlyMemory<> and avoiding using calls to C malloc, alloc and free where possible thus avoiding pointer and memory leak issues.

**Comment by yatli** [comment]
this would break the compatibility with `netfx` and interoperability with other ecosystems (e.g. python) -- ideally, a cell buffer allocated from .NET Core could be passed over to foreign runtimes.

**Comment by AlgorithmsAreCool** [comment]
@yatli For Span and Memory you just need to reference https://www.nuget.org/packages/System.Memory/ and you can keep netfx support btw.

**Comment by yatli** [comment]
Update: to clarify this, many raw pointers come from lower level C code directly and is not owned by the .NET runtime. We'd like to pass them freely between runtimes, and thus adopt commonly accessible routines for memory management.
