### ISSUE TITLE
LoadStorage Error

### ISSUE THREAD

**Issue by LiangHe-MS** [microsoft/GraphEngine#263]
Commit hash: c4c7b9acce9b2c510a2bae77b6e99dfcb95f95b2
There is an error when reloading the storage from a saved image. It can be reproduced as follows (the path is masked by hand ***):

The TSL file content:
```
cell Person
{
	int Age;
	string Name;
}
```

 The Program.cs file content:
```
class Program
{
	static void Main(string[] args)
	{
		Console.Write("Type save/load: ");
		var input = Console.ReadLine();
		if (input == "save")
		{
			foreach (var item in Enumerable.Range(0, 100))
			{
				AddPerson(item, "person-" + item);
			}
			Global.LocalStorage.SaveStorage();
		}
		else if (input == "load")
		{
			Global.LocalStorage.LoadStorage();
			Console.ReadLine();
		}
	}

	static void AddPerson(int age, string name)
	{
		Person p = new Person(age, name);
		Global.LocalStorage.SavePerson(p);
	}
}
```

The output on the first run with input 'save':
> Type save/load: save
> [ INFO    ] EchoOnConsole set to ON
> [ INFO    ] Log: changing logging directory to ***\bin\Debug\trinity-log.
> [ INFO    ] Loading Graph Engine Extensions.
> [ INFO    ] Scanning for TSL storage extension.
> [ INFO    ] TSL storage extension loaded.
> [ INFO    ] Scanning for MemoryCloud extensions.
> [ INFO    ] No MemoryCloud extension found.
> [ INFO    ] Scanning for startup tasks.
> [ INFO    ] EventLoop: Starting.
> [ INFO    ] LocalMemoryStorage is initialized in read-write mode
> [ INFO    ] Initializing logging facility
> [ INFO    ] Reading log file.
> [ INFO    ] Write-ahead-log successfully loaded. Recovered 0 records.
> [ INFO    ] Creating write-ahead log file ***\bin\Debug\storage\B\write_ahead_log\primary_storage_log_0.dat
> [ INFO    ] Saving storage to [SLOT A]
> [ INFO    ] Save storage complete, image version = 1.
> [ INFO    ] Creating write-ahead log file ***\bin\Debug\storage\A\write_ahead_log\primary_storage_log_1.dat
> [ INFO    ] Dropping write-ahead-log file ***\bin\Debug\storage\B\write_ahead_log\primary_storage_log_0.dat
> [ INFO    ] Saving cell type signatures.
> Press any key to continue . . .

The output on the second run with input 'load':
> Type save/load: load
> [ INFO    ] EchoOnConsole set to ON
> [ INFO    ] Log: changing logging directory to ***\bin\Debug\trinity-log.
> [ INFO    ] Loading Graph Engine Extensions.
> [ INFO    ] Scanning for TSL storage extension.
> [ INFO    ] TSL storage extension loaded.
> [ INFO    ] Scanning for MemoryCloud extensions.
> [ INFO    ] No MemoryCloud extension found.
> [ INFO    ] Scanning for startup tasks.
> [ INFO    ] EventLoop: Starting.
> [ INFO    ] LocalMemoryStorage is initialized in read-write mode
> [ INFO    ] Initializing logging facility
> [ INFO    ] Creating write-ahead log file ***\bin\Debug\storage\A\write_ahead_log\primary_storage_log_2.dat
> [ INFO    ] Loading storage from [SLOT A]
> [ ERROR   ] Storage signature mismatch on trunk #1.
> [ FATAL   ] Failed to load storage: Image signature mismatch.
> Press any key to continue . . .

Then the program exits with error.

**Comment by yatli** [comment]
investigating.

**Comment by yatli** [comment]
repro confirmed. debugging.

**Comment by yatli** [comment]
turns out indices fail to load. set logging level to Debug will unveil this.
a fix is being devised.

**Comment by yatli** [comment]
turns out to be a Trinity.BCL problem...
the bug remains undiscovered because MTHash::Reload simply muted the disk I/O status report.

**Comment by yatli** [comment]
here:
https://github.com/Microsoft/GraphEngine/blob/4ff6c19daa9a68211e03b9af12352fe501c1ef81/src/Trinity.C/src/Storage/MTHash/MTHash.DiskIO.cpp#L128

fixing this problem introduces this issue. oh well.

**Comment by yatli** [comment]
@LiangHe-MS I think we should add this test to build-time smoke test.
