### ISSUE TITLE
VSIX for Visual Studio 2017

### ISSUE THREAD

**Issue by shaggygi** [microsoft/GraphEngine#264]
The extension states it supports up to VS 2015.  Can you release a new version for 2017 and 2019 preview?

Thx

**Comment by TaviTruman** [comment]
@shaggygi If you can get a local build working on your machine the latest GE VS Extension is generated during the build; take a look in the GraphEngine/Build directory and you'll find the GraphEngineVSExtension package. It works with VS 2015, 2017 and 2019 Preview.

**Comment by shaggygi** [comment]
@TaviTruman thank you for the info 😄

**Comment by TaviTruman** [comment]
@shaggygi :-)
