### ISSUE TITLE
Build Application Error

### ISSUE THREAD

**Issue by LiangHe-MS** [microsoft/GraphEngine#273]
Commit hash: 341e504cad705eabb2cf6e7d015b3987a4c7206f

Trinity.dll will not be copied to the target directory when building the project, causing the following exception when running the application:

> Unhandled Exception: System.TypeInitializationException: The type initializer for 'Trinity.Global' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Trinity': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
>    at Trinity.TrinityC.__INIT_TRINITY_C__(Char* pAssemblyPath)
>    at Trinity.TrinityC.Init()
>    at Trinity.Global.Initialize_impl(String config_file)
>    at Trinity.Global..cctor()
>    --- End of inner exception stack trace ---
>    at Trinity.Global.Initialize()
>    at xxx.Program.Main(String[] args) 

It can be reproduced by rebuilding the latest code of Graph Engine and run the Friends example.

**Comment by yatli** [comment]
fixed
