### ISSUE TITLE
GraphEngine importing GML

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/GraphEngine#276]
I have a project where I need to import a large road network that is expressed/exported as GML is/are there: -

1. any existing or plans to create tools that can import terabytes of GML data.
2. any plans to provide GraphEngine extensions to perform geospatial/routing queries on graph data

**Comment by yatli** [comment]
@grahamehorner 

1. the importer prototype in the repo is already capable of chewing terabytes of RDF data. So GML support could also be built upon that (relatively easily). contributions are welcomed :)

2. very interesting idea, but outside the scope of this repo (base GE system).
