### ISSUE TITLE
Does GraphEngine support multi storage?

### ISSUE THREAD

**Issue by TCGOGOGO** [microsoft/GraphEngine#277]
In some situations, we may better not to insert everything into a graph database (may be just keep cellid in graph and save the specific data in a rdb e.g. mysql or other nosql)

**Comment by shaobin** [comment]
You can do so. There are many occasions we would like to keep only part of the data in the in-memory storage of GraphEngine. You can treat GraphEngine as a data storage and do the data joining and gluing work in C#.
