### ISSUE TITLE
OSX support?

### ISSUE THREAD

**Issue by johnberzy-bazinga** [microsoft/GraphEngine#280]
Hello,

Is there any possibility to support osx? If full osx support is difficult, would tsl codegen be a possibility? Also, is there an example of a cluster running using docker?

Thanks,
John

**Comment by shaobin** [comment]
1. As for the osx support, the short-term answer is no. Most of the system implementation is cross-platform; however, we currently do not have a test pipeline for osx and the system is largely untested on osx. 
2. For tsl-codegen, @yatli may have a better estimation.

**Comment by johnberzy-bazinga** [comment]
@shaobin Thanks for the reply. 

We were able to compile the tsl-codegen tool for osx after commenting out some of the incompatible linux libraries. Packaging is a little tricker as it looks like the flat folder structure would need to change due to name collisions.

Thanks,
John

**Comment by yatli** [comment]
@johnberzy-bazinga could you elaborate? If you mean packaging the `GraphEngine.Core` nuget package, the native assemblies can be placed in separated directories like `runtimes/osx-x64/native/libTrinity.dylib`

**Comment by johnberzy-bazinga** [comment]
@yatli I'm mainly referring to collision of `Trinity.TSL.CodeGen` in the project folder structure. I guess it would have to be hierarchical to separate the linux/osx binaries. I know the nuget handles this, but the folders the binaires get copied from have a flat structure. Also, the scripts that check for `if unix then ...` need to be modified to support the hierarchical bin/lib path.

**Comment by johnberzy-bazinga** [comment]
I'm specifically referring to this script:

https://github.com/Microsoft/GraphEngine/blob/59f814441c47511d3bee9c0427267ece2aab1666/cmake/PostBuild.cmake#L44

**Comment by yatli** [comment]
@johnberzy-bazinga you're right. The xplat cmake script does not support OSX yet. We may have to change the layout.

More problematic is `Trinity.C` where the `kqueue` implementation is lagging behind. The relevant code has been refactored several times so luckily the interface is cleaner. If you could get it working by implementing `events_kqueue.cpp` and `network_kqueue.cpp` basically you can start testing everything. The posix part, and core event dispatching loop should be osx compatible without a change.
