### ISSUE TITLE
Graph Partitioning

### ISSUE THREAD

**Issue by johnberzy-bazinga** [microsoft/GraphEngine#281]
Hello,

I'm still a little confused about how data is persisted in Graph Engine. Is there any support for partitioning graphs based on some sort of heuristic? Is this something that developers handle or is there support out of the box?

Thanks,
John

**Comment by TaviTruman** [comment]
@johnberzy-bazinga there aren't any such graph partitioning facilities OOB with the graph engine but you can easily design the notion of partition into the graph via TSL and or TSL attributes; I use both design facets to make partitioning a core manifest aspect in our GE App services. The Graph Engine persists data via storing data on disk as an especially encoded binary stream of data; if your graphs are large makes certain to reserve enough disk space. If you encode your partitioning schema in the TSL then it is saved. In my case once I made partitioning a part of the graph I subsequently had to write a code to enforce it. I use GE along with Azure Service Fabric and I keep track of organizations, users, RBAC and other such things in what I call "Partition Control Block" and "Partition Zone Control Block" objects.

**Comment by shaobin** [comment]
Thanks @TaviTruman for the nice answer to the question from the perspective of building real-world Graph Engine applications. @johnberzy-bazinga, if you want to understand the underlying mechanism, please refer to the figure 3 of the [Trinity paper](https://www.graphengine.io/downloads/papers/Trinity.pdf).
