### ISSUE TITLE
Can show some examples by using C or C++？

### ISSUE THREAD

**Issue by ggservice007** [microsoft/GraphEngine#283]
I want to use GraphEngine by C or C++ language.

How to do ?

Thanks in advance.

**Comment by shaobin** [comment]
In theory, you can use most of the Graph Engine features in C/C++. But Graph Engine does not officially provide and support user-space C/C++ APIs. If you'd like to use Graph Engine in a C/C++ program, check out the [Trinity.C](https://github.com/microsoft/GraphEngine/tree/master/src/Trinity.C) module.
