### ISSUE TITLE
Why use so many partial classes?

### ISSUE THREAD

**Issue by goroyal** [microsoft/GraphEngine#287]
Many C# source files share a same class, and I think they don't have strong relationship to stay in one class. Hard to read and maintain, a private variable can be accessed and changed in another file.

For example:

* FanoutSearchModule.cs
* FanoutSearchModule.Core.cs
* FanoutSearchModule.Web.cs
* FanoutSearchModule.Metadata.cs

All I can know is that `FanoutSearchModule` class extends `FanoutSearchBase`, which is generated by TSLs and contains many methods.

Actually, this big class merges different levels of query processing, which I know is hard to do refactoring. As first, I suggest to remove unrelated methods out of the class, for example, some static methods.

Partial class is designed to help modularization, when using it to share variables and methods among several files, it may become worse.

**Comment by goroyal** [comment]
From [MSDN](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods):

> There are several situations when splitting a class definition is desirable:
> * When working on large projects, spreading a class over separate files enables multiple programmers to work on it at the same time.
> * When working with automatically generated source, code can be added to the class without having to recreate the source file. Visual Studio uses this approach when it creates Windows Forms, Web service wrapper code, and so on. You can create code that uses these classes without having to modify the file created by Visual Studio.

**Comment by yatli** [comment]
The files are separated for different purposes. One for core protocol processing, one for initialization, one for http, etc.
