### ISSUE TITLE
what's the Sharding strategy of GraphEngine? Can I use other db backends ?

### ISSUE THREAD

**Issue by BenDerPan** [microsoft/GraphEngine#288]
what's the Sharding strategy of GraphEngine? Can I use other db backends ?

**Comment by yatli** [comment]
@BenDerPan the default sharding function is simple: `(long id) => (int)(id / 8 % Global.CloudStorage.PartitionCount`

You can override this with Global.CloudStorage.SetPartitionMethod(.) and align with the other backend.

**Comment by BenDerPan** [comment]
@yatli thanks, and how many replicas of each shard ? can we config it in trinity.xml ? :)

**Comment by yatli** [comment]
use "AvailabilityGroup" to specify the availability group id.
see:

https://github.com/Microsoft/GraphEngine/wiki/config-v2#server

**Comment by BenDerPan** [comment]
thanks, great!  close this now.
