### ISSUE TITLE
Windows Build not working as documented

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#292]
Following the build instructions for Windows the build from "tools/build.ps1" does not work:

Pwershell build results:
![image](https://user-images.githubusercontent.com/5692812/64988106-8e382080-d87f-11e9-8501-589339cb1d05.png)

The build does work from a VS 2017 Developer commond Console:
![image](https://user-images.githubusercontent.com/5692812/64988178-bc1d6500-d87f-11e9-8796-e28b89f412fc.png)

The Build does not work from a VS 2019 Developer Command Console:
![image](https://user-images.githubusercontent.com/5692812/64988235-e0794180-d87f-11e9-959d-9a6cf63a486a.png)

**Comment by yatli** [comment]
> Pwershell build results:

You don't have `cmake` in `PATH`

> The Build does not work from a VS 2019 Developer Command Console:

You don't have MSVC for VS2019.

**Comment by TaviTruman** [comment]
@yatli Yikes - yeah I got the "cmake" path issue resolved but the MSVC for VS2019 is strange; I have some parsing code written in C++ using VS 2019 and surely thought it not an issue. I will take a closer look-see.
