### ISSUE TITLE
VS2019 .net core 2.1 or 3 import GraphEngine. LIKQ package errors

### ISSUE THREAD

**Issue by shyleoking** [microsoft/GraphEngine#296]
在vs2019上建立MVC项目，无论是.net core 2.1 或 3，导入GraphEngine.LIKQ包都报错

Create MVC project on vs2019, select. net core 2.1 or 3, and import GraphEngine. LIKQ package all report errors

error info
严重性	代码	说明	项目	文件	行	禁止显示状态	禁止显示状态
错误	NU1107	Microsoft.CodeAnalysis.CSharp 中检测到版本冲突。直接安装/引用 Microsoft.CodeAnalysis.CSharp 2.8.0 到项目 WebApplication2 可解决此问题。 
 WebApplication2 -> Microsoft.AspNetCore.Mvc 2.1.3 -> Microsoft.AspNetCore.Mvc.Razor.Extensions 2.1.1 -> Microsoft.CodeAnalysis.Razor 2.1.1 -> Microsoft.CodeAnalysis.CSharp (>= 2.8.0) 
 WebApplication2 -> GraphEngine.LIKQ 1.0.8784 -> Microsoft.CodeAnalysis.Scripting 1.3.0 -> Microsoft.CodeAnalysis.CSharp.Scripting 1.3.0 -> Microsoft.CodeAnalysis.CSharp (= 1.3.0).	WebApplication2	C:\Users\shy_l\source\repos\GEWebApplication\WebApplication2\WebApplication2.csproj	1

**Comment by TaviTruman** [comment]
@shyleoking We going to need a new build that targets .NET 3.0; the current packaging is a bit out of date. I have a local build is working with .NET Core 3.0. We are going to need to have a PR in place to resolve the build; one of the repo members must update the build. You can clone the repro and execute a local build and all the bits will be on your machine.

**Comment by yatli** [comment]
looks like we should update the dependency for LIKQ.

it's probably a good idea to introduce dependabot in this repo.

**Comment by TaviTruman** [comment]
I'm looking into dependabot setup

**Comment by TaviTruman** [comment]
Oh wow, the dependabot setup is very simple; I don't have access to the GE Azure CD/CI DevOps environment, so a member of the GE Team will need to update it.

**Comment by shaobin** [comment]
The toolchain has been updated; this issue is not relevant anymore. I will close this thread.
