### ISSUE TITLE
Need to Update Graph Engine Build Targets: Include .NET Core 3.0 and .NET Standard 2.1

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#297]
Just an FYI to the Graph Engine community. Looks like it is time to update the Build Targets: .NET Core 3.0 and .NET Standard 2.1 and to publish updated Nuget Packages. We are blocked in using the Graph Engine with .NET Core 3.0 Desktop and Console Apps. We still can't use GE on macOS, iOS or Android. We are behind on .NET Core for Service Fabric and integration in a couple of places as well. I've got a couple of PR in the pipeline that addresses some of these issues. Please feel free to correct me if I've got these facts wrong here.

**Comment by yatli** [comment]
Hi Tavi,

Thanks for your comments. I'll reply to your points inline.

> We are blocked in using the Graph Engine with .NET Core 3.0 Desktop and Console Apps

I don't see why a `netstandard2.0` project cannot be used with .NET Core 3.0. Any specific error you've encountered?

> We still can't use GE on macOS, iOS or Android

GraphEngine is designed and built specifically for the `x64` architecture. There's no plan at the moment to port it to the mobile platforms.
The macOS port needs some work, mostly in the network subsystem. I've rewritten that part for Windows and Linux a while ago.

> We are behind on .NET Core for Service Fabric and integration in a couple of places as well. I've got a coupel of PR in the pipeline that address soem of these issues.

PRs are welcome, as always. :)

**Comment by TaviTruman** [comment]
@yatli Thanks for the quick responses. I am getting some build errors and some very strange execution errors in Service Fabric runtime. I'm still researching and will create a separate issue when I have the problem properly documented. I understand the iOS and Android reservations but really do need to run in the macOS.

**Comment by TaviTruman** [comment]
I had to reinstall the cmake software and that solved the problem with the GraphEngine build not working from Powershell.
