### ISSUE TITLE
Build and execution errors in Service Fabric .NET 3.0 Services

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#298]
@yatli Thanks for the quick responses. I am getting some build errors and some very strange execution errors in Service Fabric runtime. I'm still researching and will create a separate issue when I have the problem properly documented. I understand the iOS and Android reservations but really do need to run in the macOS environment.

_Originally posted by @TaviTruman in https://github.com/microsoft/GraphEngine/issues/297#issuecomment-540293282_

**Comment by TaviTruman** [comment]
@yatli I'm still testing the migration of my native GE services into GE/SF integrations and running into a few (seamingy critical) issues. Here I am trying to build a .NET Core 3.0 Stateless/Stateful services and getting these warnings. I'm still gathering documentation so I will come back to you item and update it.

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	**Package 'GraphEngine.ServiceFabric.Remoting 2.0.10057**' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.	IKW.GraphEngine.TripleStoreRemotingClientService	I:\IKW-Azure-GE-SF-Dev\IKWSemanticTripleStoreGraphEngineSFApp\IKW.GraphEngine.TripleStoreRemotingClientService\IKW.GraphEngine.TripleStoreRemotingClientService.csproj	1

**Comment by yatli** [comment]
we should upgrade `Microsoft.ServiceFabric.Services.Remoting` to `netstandard2.0` compatible version

**Comment by TaviTruman** [comment]
Yes, I've made the change locally and things have improved; there's another item to update and we should be golden. I've made local changes in my local repro and it has improved the stability of the GE running in the SF environment. I will submit a PR for this change.
