### ISSUE TITLE
Problem with running multiple Client

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#304]
Server responses with rsp code=100
[ INFO    ] LocalMemoryStorage is initialized in read-write mode
[ INFO    ] Initializing logging facility
[ FATAL   ] Cannot open write ahead log for read. Exiting.

This looks like a concurrency problem but it only happens in I run more than one instance of a client. I can run one instance of my WPF client and instance of the Console App both connected to the same server and no write ahead log error is generated. My guess is that there is some type of setting I must be missing. Can anyone point me in the direction look for answers.

![image](https://user-images.githubusercontent.com/5692812/67602632-e6d6c500-f72b-11e9-8c18-b7ecb5d8a198.png)

**Comment by TonyLo1** [comment]
I ran into the same issue today. Running DistributedHashtable sample in embedded mode. The issue appears when attempting to run two separate processes: one for server and one for client.

When running the sample as a single process the issue does not appear. So it does indeed seem to be related to a concurrency problem. I can work around it, so no practical issue for me at this time.

**Comment by TaviTruman** [comment]
@TonyLo1 Hey, tony the Graph Engine server API is powerful and a bit unorthodox in its raw form; the DistributedHashTable sample is purposed only to demonstrate how one can implement a distributed hash table - I'm certain that you understand that; however, what is not clearly described in any of the samples is what requirements are to host server-side so that multiple server instances and clients works. In my original post, I made the assumption that I could just fired-up an additional server and client instances but that is not the right approach; after many trial and error attempts, I finally learned the importance of the **TrinityConfig** object and the role it plays in the managing the Trinity runtime. Also depending on the "Server" model and how you host the server implementation, your implementation will change some as well. So as it turns out in my original post there is no concurrency issue - it was an end-user problem. I've been using the Graph Engine for 3 years now and I run into this type of misunderstanding quite a bit. The technology does work but at this point, you have to explore, dig around the source code and be curious. We are working on improving the documentation and samples and better unit and integration testing. The core of the technology seems to test only the very core; a great deal more testing and better documentation are required.

**Comment by TaviTruman** [comment]
@TonyLo1 Take a look in my repro and find the **Trinity.Client.TestServer** solution. I've got the GE Server, a .NET Core 3.1 Console App, and .NET Core 3.1 WPF App all running at the same time; the clients are running the same code. There also some I/O routed to the VS output window. This is an example of "multi" and parallel-tasking code working seamlessly with the GE - no concurrency issues at all.

![image](https://user-images.githubusercontent.com/5692812/78589870-c2f8ce80-77f5-11ea-939b-3fcda6c13041.png)

![image](https://user-images.githubusercontent.com/5692812/78589919-d7d56200-77f5-11ea-9499-e98f50eab3b8.png)
