### ISSUE TITLE
Question: I thought the GraphEngine.DataImporter supported .CSV file 

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#305]
@yatli I thought the DataImporter supported ".CSV" file for data import; when I point the tool to such file the program throws an exception - when I look at the code, it does not look like CSV file format is supported. I'm investigating the problem now but I thought I'd ask.

**Comment by yatli** [comment]
The importer does support CSV. You'll have to define a TSL to match the fields.

**Comment by TaviTruman** [comment]
Okay, got it. I was not sure of the requirement of the TSL + CSV file.
