### ISSUE TITLE
Wrong Async RPC Method called [BUG]

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#308]
The wrong async method is being called! Very frustrating to encounter this type of bug at this stage in development. I have a medium-size complex WPF/MVVM project using Trinity/GraphEngine; I have integrated GraphEngine using a modular MVVM design pattern using PRISM and Castle Windsor DI. I have created a number of .NET472 assemblies that embody data segments using the Separation of  Concerns design idiom. 

![image](https://user-images.githubusercontent.com/5692812/69196456-61a0bf00-0ae3-11ea-9624-c900eea3ecdb.png)

I have created CommunicationShell, a wrapper around the Trinity APIs that set up the communications stack; the CommunicationShell is injected into each ViewModel - this is done so as to avoid duplicate code and to only have a single established environment for the entire application and all ViewModel instances.

![image](https://user-images.githubusercontent.com/5692812/69196727-25ba2980-0ae4-11ea-89b9-03f3aa1e59eb.png)

In this code segment the Trinity client-side environment is established:

![image](https://user-images.githubusercontent.com/5692812/69196830-7b8ed180-0ae4-11ea-878d-3525063b9d62.png)
 
You can see that I'm using the module Trinity dynamic server composition API to register each communication module; I am also getting each module implementation setting up reactive observables against each module. 

Here is the error:

![image](https://user-images.githubusercontent.com/5692812/69197084-433bc300-0ae5-11ea-92fa-62c5a8d3f335.png)

In this existing codebase the RPC method "**_PushContactDataModelAsync_**" is never called but as you can see here it has been called by the Trinity runtime!

Here is the only actual RPC method called in the app at this time:

![image](https://user-images.githubusercontent.com/5692812/69197241-ba715700-0ae5-11ea-9120-105d20cb6817.png)

As you can see I make the call to "QueryUserAuthInfoAsync" - this is a bug. 

I have a lot of material regarding this bug and I am willing to connect via LiveShare in VS 2019 so that it can be observed directly. Please let me know what other data and or information you need to move forward in investigating the problem.

**Comment by yatli** [comment]
Quick guess: stale assembly?

Do these methods have the same signature?

**Comment by TaviTruman** [comment]
Here is the signature of the two methods - I don't think they aren't the same:

[ContactDataModel.zip](https://github.com/microsoft/GraphEngine/files/3871104/ContactDataModel.zip)
[UserAuthenticationProtols.zip](https://github.com/microsoft/GraphEngine/files/3871105/UserAuthenticationProtols.zip)

**Comment by TaviTruman** [comment]
@yatli I forgot to mention that the purposed RPC method  (the right method),  is called along with the wrong method being called; just to make it even more strange.

**Comment by TaviTruman** [comment]
I went looking through the Graph Engine source I could not find examples of where multiple modules are loaded into a single TrinityServer instance; so, I am going to leave this issue open for now - this is a bug. 
In **FanoutSeach** and **DynamicCluster** only a single module instance is ever used - it works and I have it working as well, so I'll follow the design examples I found in the aforementioned projects and just use one module; that makes the TSL files larger than I'd like them to be and I'll need to run more than one TrinityServer. I can message between TrinityServer instances to coordinate computations.

**Comment by TaviTruman** [comment]
After lots of testing and re-reading the available docs I now understand how the API works and why it works the way it does. I studied and traced through a lot of code via debugging; I'm working on some documentation to more clearly detail my findings. I was using the API incorrectly.
