### ISSUE TITLE
GraphEngine.Azure.BlobStorage？

### ISSUE THREAD

**Issue by shyleoking** [microsoft/GraphEngine#309]
VS2017 has errors during compilation：
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not add the file 'C:\Users\leoking\CMakeBuilds\a6144ce7-852c-c637-b52b-28472c6798df\build\x64-Debug (default)\GraphEngine.Azure.BlobStorage.2.0.10126.nupkg' to the zip package 'C:/Users/leoking/CMakeBuilds/a6144ce7-852c-c637-b52b-28472c6798df/build/x64-Debug (default)/GraphEngineVSExtension.vsix'. Could not find file 'C:\Users\leoking\CMakeBuilds\a6144ce7-852c-c637-b52b-28472c6798df\build\x64-Debug (default)\GraphEngine.Azure.BlobStorage.2.0.10126.nupkg'.	TrinityVSExtension.VS2017	C:\Users\leoking\Source\Repos\microsoft\GraphEngine\src\Trinity.VSExtension\TrinityVSExtension\VSSDK

**Comment by TaviTruman** [comment]
@shyleoking I am not able to reproduce the error you sited above; I would try to run the build script again from a fresh download from the repro:

![image](https://user-images.githubusercontent.com/5692812/70962642-bb40ce80-203a-11ea-9c23-4e5051516110.png)

**Comment by shyleoking** [comment]
solution is   Trinity.VSExtension.VS2017

**Comment by shyleoking** [comment]
@TaviTruman  I run build.ps1 


![image](https://user-images.githubusercontent.com/3367161/71047946-6a36f480-2178-11ea-81f1-cdf863fe855c.png)

**Comment by TaviTruman** [comment]
@shyleoking you need to include the "**CMake**" feature in the Visual Studio setup.

**Comment by shyleoking** [comment]
Thank you. It's a success. Thank you very much  @TaviTruman

**Comment by TaviTruman** [comment]
@shyleoking Looks like we can close this one too.

**Comment by shaobin** [comment]
Thanks @TaviTruman.
