### ISSUE TITLE
cell 类型无法运行

### ISSUE THREAD

**Issue by shyleoking** [microsoft/GraphEngine#316]
my code

cell MyCell
{
	int A;
	List<MyStruct> Structs;
}

struct MyStruct
{
	int B;	
}

but at Program

![image](https://user-images.githubusercontent.com/3367161/78955771-e469fb00-7b12-11ea-92d5-e8aea4c73f5c.png)

**Comment by TaviTruman** [comment]
@shyleoking It looks like you're missing a using statement; can you show your complete program code?
