### ISSUE TITLE
Updated Build Fails

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#324]
I just performed a fresh download, ran the build and the Service Fabric projects fail:

![image](https://user-images.githubusercontent.com/5692812/84796963-1e8dc800-afae-11ea-8de2-5f6c83ef4052.png)
Here's what my "dotnet" environment looks likes:

![image](https://user-images.githubusercontent.com/5692812/84797095-49781c00-afae-11ea-9788-71355ca109bb.png)

"dotnet" version:

![image](https://user-images.githubusercontent.com/5692812/84797205-67de1780-afae-11ea-9bf8-415eb8708e65.png)

Service Fabric SDK version:

![image](https://user-images.githubusercontent.com/5692812/84797439-aecc0d00-afae-11ea-966e-1bb4be8cc44a.png)

**Comment by TaviTruman** [comment]
I was able to get a partial fix this problem by doing the following:
I tried these things incrementally:

1. Ran this command from Powershell:  "dotnet nuget locals all --clear"
![image](https://user-images.githubusercontent.com/5692812/84814981-2ad24f00-afc7-11ea-99ab-3cf610b4ab35.png)

2. Cleared All Nuget Cache(s) within VS-2019 because the first command did not completely clear the Nuget Cache;
3. I had to de-select all Nuget Packages except for "nuget.org" and "Graph Engine OSS Local"; otherwise, the Graph Engine build tries to look for packages and fails. NOTE: the build does not use a "nuget.config" file so it will pick-up what's been cached.

![image](https://user-images.githubusercontent.com/5692812/84814921-0d04ea00-afc7-11ea-86bd-82395fc7b22b.png)

This improved the quality of the build; the GraphEngine.ServiceFabric section ran executed without error; however, a new build error occurred:

![image](https://user-images.githubusercontent.com/5692812/84815582-15a9f000-afc8-11ea-8347-5c8cc7f63aa4.png)

**Comment by TaviTruman** [comment]
I just re-ran the build after the last error - I made no changes and the build ran to completion without error. So, it looks like things are cached and put in place incrementally during each run of the build and it finally ran to completion.

**Comment by MasakaGray** [comment]
Hey TaviTruman, I ran into another issue when I tried to run .\tools\build.ps1.
Do you have any idea about it? Thanks a lot. Xia 

<img width="838" alt="Screenshot 2020-06-18 at 15 01 43" src="https://user-images.githubusercontent.com/26504936/85029955-c9e87980-b174-11ea-870a-17cbffba6bee.png">

**Comment by TaviTruman** [comment]
@XiaAlexFang Yikes - Yeah, I just got the same thing. I working to understand to resolve the problem now,

**Comment by msylvestre** [comment]
I got it to build by running the cmake command directly, skipping the remaining of the build.ps1 script....

**Comment by TaviTruman** [comment]
Yeah - I was able to do that too but the build script does some other important task; I think I've found the problem and the solution so I will update here later on.

**Comment by TaviTruman** [comment]
Okay, I was able to resolve the problem by doing the following:

1. download the "dotnet" uninstaller and remove all dotnet runtimes and SDKs.
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-uninstall
2. Uninstall VS 2019
3. Re-install VS 2019

The build works!
