### ISSUE TITLE
[Ms Graph] Getting error from Ms graph send mail API

### ISSUE THREAD

**Issue by Vishnuvk33** [microsoft/GraphEngine#329]
Hi team,

      Getting the below error 'Code: generalException  Message: An error occurred sending the request. ' from Ms graph send mail Api.
     It is not occurring every time. 

     Able to telnet graph.microsoft.com 443 from the hosted server.
   
    Please let me know, any thing needs to be checked from our side.

Thanks,
Vishnukumar M

**Comment by TaviTruman** [comment]
@Vishnuvk33 - I think you may be looking for the Microsoft Graph API team; not to be confused with this GraphEngine repo.

**Comment by TaviTruman** [comment]
@Vishnuvk33 please close this issue as this is not a Microsoft Graph API problem.
