### ISSUE TITLE
.Net 5?

### ISSUE THREAD

**Issue by alenas** [microsoft/GraphEngine#331]
Are you planning to update to .net 5 and maybe even VS 2019 extensions?
I am doing a new project where I need custom graph traversing, so I see a lot of value in TSL and graph engine, but don't want to start using GE if it is not going to be updated anymore.
If not GE what would you recommend to look at?

**Comment by TaviTruman** [comment]
@alenas Hello - yes, I've already moved to support both .NET 3.1 LTS and .NET 5. I've also updated the VS 2019 Extension with a few improvements and bug fixes. We made a lot of updates to Graph Engine and I will post updates in a week or new with the next Nuget Packages. The GE is not abandoned, and you can expect to see updated docs, a new developer's guide, a TSL modeling design guide and enhancements to Graph Engine for Service Fabric, and more options for Graph Traversal with using LIKQ.

**Comment by alenas** [comment]
Good to hear @TaviTruman. I can help you guys with bug fixes or testing, if you have something that is easy to delegate.

**Comment by TaviTruman** [comment]
@alenas That's awesome as there's a lot to do. We need help with testing for sure; keep an eye out as we are working to produce docs that describe what needs to be done.

**Comment by alenas** [comment]
Hi. Any news?

**Comment by TaviTruman** [comment]
@alenas Yes, we have the .NET 5 build ready to go; we just want to fix a few things in the CI/CD build and we will have a new place to download NuGet packages. I am working to release it on Friday morning.

**Comment by alenas** [comment]
@TaviTruman I guess you need some help 😄

**Comment by TaviTruman** [comment]
@alenas Hey there - I've got it done; however, I've been out due to surgery. I will make the new build and NuGet package available come Monday new week,

**Comment by alenas** [comment]
No worries @TaviTruman. Get well. Your wellbeing is more important than this.

**Comment by TaviTruman** [comment]
@alenas I've got the new build ready it supports. netcoreapp2.0,. netcoreapp3.1 and .net5.0. I will try to merge lots of updates today.

**Comment by alenas** [comment]
Cool. I will wait patiently ;)

**Comment by mwherman2000** [comment]
bump :-)

**Comment by TaviTruman** [comment]
@alenas @mwherman2000 I have the build ready to go but need to set up a new NuGet Feed; I should have it ready tomorrow.

**Comment by alenas** [comment]
bump :)

**Comment by TaviTruman** [comment]
Sorry guys - I've been out for a few weeks due to surgery; I will get this done this week.

**Comment by mwherman2000** [comment]
I've settled in on .NET CORE 3.1 for a variety of reasons ...mostly dependencies on C# OSS project dependencies.

**Comment by TonyLo1** [comment]
@TaviTruman HI pal, hope you recovered form your surgery now. Any news on the the updates ?

**Comment by TaviTruman** [comment]
@TonyLo1 Hello here :-) I'm feeling much better now; took me way longer to recover from surgery. To answer your questions yes I'm ready to publish this week.

**Comment by TonyLo1** [comment]
@TaviTruman  that’s great news on both fronts. Thank you for your tireless efforts to improve the project.

**Comment by TaviTruman** [comment]
@TonyLo1 I'm unable to apply direct updates to this repo but all I maintain an up-to-date repo here: https://github.com/InKnowWorks/GraphEngine. There are many updates here as well as bug fixes as well. .NET 5 and .NET 6 support is ready. I've also added a lot of new capabilities - we have been working to update code generation so that we can take advantage of the latest advances in .NET and C#; we are also working on native client-side code for Java 17 and RUST. We are also looking to see what support for Python there is. I've written a Developers Guide but it is still a work-in-progress. I will provide an updated Readme file and general news on my repo home page.

**Comment by TonyLo1** [comment]
@TaviTruman Awesome!

**Comment by TaviTruman** [comment]
@TonyLo1 I'm going to post a new build today. I'll send out a note regarding this build this evening.

**Comment by TonyLo1** [comment]
@TaviTruman Hi, did the new build get posted? If so I must be looking in the wrong location.

**Comment by TaviTruman** [comment]
@TonyLo1 Hello, Tony. I just pushed a new update that fixes a build problem I had with .NET 5 bust that is fixed now. I'm still failing on a couple of .NET 6 issues so I hope to have those fixed later this week. I am going to generate a new Nuget package so that you don't have to build locally get the Nuget built.

**Comment by TonyLo1** [comment]
@TaviTruman an updated Nuget package is really all i need :) Thanks

**Comment by engine5d** [comment]
@TaviTruman Greate job. I use neo4j in past years.  As a .net fans, I expect an excellect  graph db/engine .net related tightly all the time.  But this repo no update too long time.

**Comment by TaviTruman** [comment]
@engine5d Thanks! neo4j is a great technology. Graph Engine is a fantastic technology but quite different when compared to technologies like neo4j. Microsoft does not seem to have any resources committed to this repo as you can see there is very little movement here. I do have a forked version of this repo: https://github.com/InKnowWorks/IKW-GraphEngine, and we are working on a lot of upgrades. We are working to continue the amazing work that Microsoft Research started some ten years ago. I have a small team working on improvements but will be adding more resources this year and into the future.

**Comment by mwherman2000** [comment]
I'm curious about the kinds of software systems people are using the Trinity GraphEngine for?

Personally, I'm using Trinity to design and implement a decentralized agent architecture based on the W3C decentralized identifier and verifiable credential draft specifications.

**Comment by engine5d** [comment]
@mwherman2000  We are planing to use GE for storing and query digital-twin data in local or distribute environments. we need to test the GE max capability for load digital-twin billions of instances. @TaviTruman

**Comment by TaviTruman** [comment]
Here is a link to a commercial application that is 100% Graph Engine: 

- https://www.rocketurbiz.com/overview
- https://www.rocketurbiz.com/developers

Here is what we are about ready to release in our next Graph Engine release:

- https://github.com/InKnowWorks/IKW-GraphEngine

We are building a tool-chain for ontology-based software engineering and the Graph Engine sits at the center."

- https://www.inknowworks.com/

**Comment by shaobin** [comment]
I've bumped .NET from 3.1 to 6.0. I will close the issue later if you don't have further questions with regard to .NET support. Thank you, @alenas @TaviTruman @mwherman2000 @TonyLo1 @engine5d!
