### ISSUE TITLE
build.ps1 on Windows 10: CMake Error: Unknown argument --host=x64

### ISSUE THREAD

**Issue by mwherman2000** [microsoft/GraphEngine#332]
```
PS C:\ge\GraphEngine> .\tools\build.ps1  -VS2019
GraphEngine repo root:         C:\ge\GraphEngine
TRINITY_CMAKELISTS             C:\ge\GraphEngine\CMakeLists.txt
TRINITY_OUTPUT_DIR:            C:\ge\GraphEngine\bin
[x] Removing: C:\ge\GraphEngine\bin
[x] Removing: C:\ge\GraphEngine\build


    Directory: C:\ge\GraphEngine


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2021-06-03   4:23 PM                build
CMake Error: Unknown argument --host=x64
CMake Error: Run 'cmake --help' for all supported options.
Error: could not load cache
```

**Comment by mwherman2000** [comment]
I made a copy of build.ps1 and removed the 2 references to --host=x64

Unrelated, also make sure you:
1.  start PS with Run as Administrator
2.  have downloaded all of the prerequisites ...esp. the Windows 10 SDK.

**Comment by TaviTruman** [comment]
@mwherman2000 I'm on Windows 10 Enterprise and have no issues with the build script when run in PowerShell. 
1. no problem with "--host=x64 flag
2. Windows 10 SDK installed
![image](https://user-images.githubusercontent.com/5692812/120879421-096fc780-c578-11eb-91aa-b21f9334831c.png)

![image](https://user-images.githubusercontent.com/5692812/120879385-c877b300-c577-11eb-818d-27a8b9d0c96e.png)

3. PowerShell and dotnet --info

![image](https://user-images.githubusercontent.com/5692812/120879321-5e5f0e00-c577-11eb-999f-e4d370feb4e4.png)

4. Windows OS Information

![image](https://user-images.githubusercontent.com/5692812/120879245-e5f84d00-c576-11eb-9918-d88a910b8661.png)

5. You must have the latest version of CMake installed.

![image](https://user-images.githubusercontent.com/5692812/120879560-1d67f900-c579-11eb-84a8-556abd88570b.png)
