### ISSUE TITLE
[How to] Run 2 Trinity servers on the same Windows 10 laptop at the same time?

### ISSUE THREAD

**Issue by mwherman2000** [microsoft/GraphEngine#333]
I have two Trinity's VS2019 projects: one implements a "key management server" and the second implements a "resource server" ... completely separate projects/executables ... separate HTTP ports ... separate TSL definitions.

What's the best way to do this? ...besides combining everything.

**Comment by mwherman2000** [comment]
It's not pretty but the following seems to enable the running of 2 (or more) instances of different Trinity servers at the same time...
```
            TrinityConfig.HttpPort = 8080 + 1;
#pragma warning disable CS0612 // Type or member is obsolete
            TrinityConfig.ServerPort = 5304 + 1;
#pragma warning restore CS0612 // Type or member is obsolete

            TDWKMSServer kmsServer = new TDWKMSServer();
            kmsServer.Start();
```

**Comment by TaviTruman** [comment]
@mwherman2000 Looks like you want to set up a GE Cluster of two instances on the same machine; have you tried to create a configuration file for the two machines? I know there are a lot of examples using the "trinity.xml" XML file. I can send you an example config file. FYI - I run on one of our Azure VM instances some 15 GE services as Windows Services.

**Comment by TaviTruman** [comment]
@mwherman2000 did you get this figured out?

**Comment by mwherman2000** [comment]
The 2 port approach is working for now.

**Comment by mwherman2000** [comment]
For the record, the following doesn't work: you can't try to start two instances of your server from the same Windows process...
```csharp
            TrinityConfig.HttpPort = 8080 + 1;
#pragma warning disable CS0612 // Type or member is obsolete
            TrinityConfig.ServerPort = 5304 + 1;
#pragma warning restore CS0612 // Type or member is obsolete
            var agent8081 = new NFELocalStorageAgentImplementation();
            agent8081.Start();

            TrinityConfig.HttpPort = 8080;
#pragma warning disable CS0612 // Type or member is obsolete
            TrinityConfig.ServerPort = 5304;
#pragma warning restore CS0612 // Type or member is obsolete
            var agent8080 = new NFELocalStorageAgentImplementation();
            agent8080.Start();
```

**Comment by TaviTruman** [comment]
Correct IP ports are not shared. You should explore Availability Groups (Cluster) if you need redundancy and horizontal and or vertical scaling.
