### ISSUE TITLE
[Bug Report] There is a little bug in Network lib

### ISSUE THREAD

**Issue by qingzhu521** [microsoft/GraphEngine#335]
In our experiment, we found when we load a large cell to client. The client will break. And the server will continue without loading the large cell. As we debug, we found there is a bug in src/Trinity.C/src/Network/Network.cpp:220. There is no way for Network::send_async(p_sock) to return E_SUCCESS, but the left hand of == is E_SUCCESS. It should be E_RETRY.

**Comment by TaviTruman** [comment]
@qingzhu521 Thanks for reporting this! I will include a fix and testing in this week's build.

**Comment by qingzhu521** [comment]
@TaviTruman which branch is up to data branch?

**Comment by TaviTruman** [comment]
@qingzhu521 https://github.com/InKnowWorks/GraphEngine
