### ISSUE TITLE
Website certificate is not valid 

### ISSUE THREAD

**Issue by leandrobrunner** [Microsoft/GraphEngine#345]
When trying to access the website, the browser displays an invalid certificate message.

![image](https://user-images.githubusercontent.com/1664991/173686643-4efe6faa-7788-49f4-82b0-259e00f8a962.png)

**Comment by shaobin** [comment]
@leandrobrunner Thank you for reporting this. I can access the website without any issue on multiple devices. I've refreshed the certificates anyway. Could you retry? If it still doesn't work, could you try accessing it on a difference device?

Here is the SSL report generated by SSL Labs: https://www.ssllabs.com/ssltest/analyze.html?d=www.graphengine.io

**Comment by shaobin** [comment]
@leandrobrunner Could you help confirm whether the issue is fixed? 

@TaviTruman If you happen to notice this, could you kindly help check the website on your device?

**Comment by TaviTruman** [comment]
@shaobin @leandrobrunner https://www.graphengine.io/ is clean - the certificate is good. No errors were reported.

![image](https://user-images.githubusercontent.com/5692812/174399091-e261de15-0f4e-4cf9-8003-aabdb6be3d0d.png)

**Comment by leandrobrunner** [comment]
@shaobin, @TaviTruman Thanks for checking this out!

Now it is working perfectly on all my devices and browsers, maybe it was a problem with DNS propagation?
