### ISSUE TITLE
Public website certificate is not valid

### ISSUE THREAD

**Issue by karayakar** [Microsoft/GraphEngine#362]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/2394360/191065757-d439668a-59dd-4d9d-9f5b-010279f52531.png">

**Comment by TaviTruman** [comment]
I can't see nor am I experiencing any problems with the website certificate.

![image](https://user-images.githubusercontent.com/5692812/191071614-75e6db53-e6e1-4064-95e6-6204d3657f75.png)

**Comment by karayakar** [comment]
I think certificate is expired. 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/2394360/191099495-001cb0fc-e9f8-45a2-9857-1a38b5a6ba22.png">


is fingerprint on that cert same on your side?

<img width="392" alt="image" src="https://user-images.githubusercontent.com/2394360/191099618-4b35f89d-0bd2-4a3e-aaf4-b7f30958c731.png">

**Comment by karayakar** [comment]
I am still getting same error, 
 
<img width="509" alt="image" src="https://user-images.githubusercontent.com/2394360/191099983-8891dd92-ca44-4fa8-98a0-691a7f4f3e25.png">

 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/2394360/191099784-69dce815-a979-495b-9881-241ca43e2827.png">

**Comment by dee-me-tree-or-love** [comment]
Unfortunately experiencing the same issue as @karayakar. 🙏 
The discussion looks very similar to https://github.com/microsoft/GraphEngine/issues/345.

> The certificate description suggests that it expires on `Expires On	Wednesday, 2 March 2022 at 10:21:31`.
>
> <img src="https://user-images.githubusercontent.com/12134172/191371087-cd73b956-17eb-46f9-87b7-ed9ec3c84bef.png" width="450">

**Comment by TaviTruman** [comment]
@shaobin Is this something you can look into, please? No response here might negatively impact confidence in the repo and hinder devs' ability to get other devs and or management.

Thanks!

Tavi

**Comment by Diaaz** [comment]
I cannot open the website at all. Edge says the certificate is revoked.

**Comment by TaviTruman** [comment]
**I am not able to recreate the problem.** I am trying to support the GE community, but there is little I can do about it. I know that the MS GE team is about other developments. We need to generate more interest to get the attention needed.

**Comment by TaviTruman** [comment]
Okay it finally happened to me as well; the GraphEngine.io website certificate has expired!

![image](https://user-images.githubusercontent.com/5692812/228633669-e7b94358-f81b-4baf-a999-bf9bd6198a2f.png)

@shaobin Can you investigate this please?

**Comment by TaviTruman** [comment]
Looks to be fixed now; can others confirm?

**Comment by karayakar** [comment]
yes fixed now, verified. Thanks.
