### ISSUE TITLE
Unable to load shared library 'Trinity' or one of its dependencies. when compiling on Ubuntu 22.04 or Wsl 

### ISSUE THREAD

**Issue by dinorghub** [Microsoft/GraphEngine#375]
when using one of the sample on ubuntu am getting the following exception : 
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Trinity.Global' threw an exception.
  Source=Trinity.Core
  StackTrace:
   at Trinity.Global.get_LocalStorage()
   at Friends.Friends.Main(String[] args) in C:\repos\trinity\GraphEngine\samples\Friends\Program.cs:line 70

  This exception was originally thrown at this call stack:
    Trinity.TrinityC.Init()
    Trinity.Global.Initialize_impl(string)
    Trinity.Global.Global()

Inner Exception 1:
DllNotFoundException: Unable to load shared library 'Trinity' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libTrinity: cannot open shared object file: No such file or directory

the project compiles ,but cannot run , on windows no issues.

even when using our own project i see the same behavior : 

 Error Message:
   System.TypeInitializationException : The type initializer for '******rinityGE.Graph' threw an exception.
---- System.TypeInitializationException : The type initializer for 'Trinity.Configuration.StorageConfig' threw an exception.
-------- System.TypeInitializationException : The type initializer for 'Trinity.CTrinityConfig' threw an exception.
------------ System.DllNotFoundException : Unable to load shared library 'Trinity' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libTrinity: cannot open shared object file: No such file or directory

do we need additional libraries on linux specifically on ubuntu ?

**Comment by TaviTruman** [comment]
Yikes! I will take a look at this today!

**Comment by TaviTruman** [comment]
Just getting back around to looking at this; I'll post an update tomorrow.

**Comment by shaobin** [comment]
@dinorghub I have updated the project to support the latest stable version of .NET (.NET 7.0) and tested it on Ubuntu 22.04. Could you please try using the most recent source code?

**Comment by shaobin** [comment]
I believe this issue has been resolved, so will close the issue. Thank you, @dinorghub @TaviTruman!
