### ISSUE TITLE
What is the most canonical way to represent a relationship?

### ISSUE THREAD

**Issue by swasheck** [microsoft/GraphEngine#47]
In the Friends example, relationships are implied by storing the cell id (or a List<long> of cell ids) in the related nodes. In the Freebase example, though, there's the notion of a `[GraphEdge]` that's introduced. I was hoping the documentation (and perhaps here), we could get a clear understanding of how to properly model relationships/edges using GraphEngine.

**Comment by leoxia** [comment]
@swasheck I would like to say it depends on the application:-) In the Friends example, the "Friendship" is actually a hyper-edge. Persons (i.e. Character cells) that are pointed to by a Friendship cell are friends with each other. Another way of specifying relationships is to "connect" cells directly. For example, we can use the following schema to model the relationship between a Company and its Employees.
```
cell Company {
  List<long> employees; // list of employee cell ids
}
cell Employee {
}
```

As for the `[GraphEdge]`, it is an attribute that is used by [LIKQ](https://github.com/Microsoft/GraphEngine/tree/master/src/LIKQ) to do the "Fanout Search". More specifically, a fanout search process will only follow the "relationships/edges" that are marked as "GraphEdge" to proceed.
