### ISSUE TITLE
Cant find  using Trinity.Extension.DistributedHashtable;

### ISSUE THREAD

**Issue by jorgepluna** [microsoft/GraphEngine#50]
Where is this lib?

**Comment by yatli** [comment]
@jorgepluna I believe this is a VS related issue. The project builds fine but Intellisense reports the error. Currently there is a workaround, to unload the project and reload again, and then VS will pick up the TSL namespace and all the constructs within.

**Comment by jorgepluna** [comment]
Thanks. I can see TSL no problem. I can't see Trinity.Extension for your DistributedHashtable sample

**Comment by jorgepluna** [comment]
It worked for Extention as well. Thanks
