### ISSUE TITLE
Support for Visual Studio 2017

### ISSUE THREAD

**Issue by tedvanderveen** [microsoft/GraphEngine#57]
Currently Graph Engine VSExtension only supports Visual Studio 2012, 2013, 2015

**Comment by TaviTruman** [comment]
I've been using it in vs 2017 for months now.

**Comment by PhilPJL** [comment]
@TaviTruman How are you using it in VS 2017?  The extension doesn't install.

**Comment by yatli** [comment]
@PhilPJL please try to build the extension from `master`

**Comment by PhilPJL** [comment]
@Yatli.  Ok thanks, will do. What's the ETA on the next preview?

**Comment by yatli** [comment]
We're now packing all the nuget packages into the SDK vsix so we've got to make sure everything is functioning. Cannot be so sure about a release ETA, sorry :)

**Comment by PhilPJL** [comment]
@yatli.  Ok.  If want to ask various dumb questions, is emailing graphengine@microsoft.com a good place?

**Comment by yatli** [comment]
feel free to send any query to us! or you can talk to me directly here: yatli@microsoft.com

we've got a GitHub bot connected to our Teams channel, so posting in the issues section will also get me notified.

**Comment by PhilPJL** [comment]
Thanks, I'll get some questions together and send them over next week.

**Comment by yatli** [comment]
Will be there.
I'm closing this issue now, as VS2017 support is getting ready.
