### ISSUE TITLE
How to host Graph Engine in one of the Azure SaaS  components

### ISSUE THREAD

**Issue by tedvanderveen** [microsoft/GraphEngine#58]
How can we run Graph Engine from Azure SaaS environment, like for example Service Fabric?
We prefer not to host/maintain our own VM's, so what would be our options using a services component in Azure?

**Comment by TaviTruman** [comment]
Yeah I've been doing that for months now. There's a couple of ways to do it and I'll send you come code to help you get started. The proper way is to implement a custom connection provider and I've got mind working but it still needs a bit of work. I have also written native set vs extension for service fabric workflow and it should be ready next week. I am traveling on business this week so I'll be slow getting around to getting the code up to GitHub.

Tavi Truman
Sent from my Windows 10 phone

**Comment by tedvanderveen** [comment]
@TaviTruman yes please forward your code to my mail ted@vanderveen.net, I may be able to support your efforts. Maybe setup a Fork from this repo to work from?

**Comment by TaviTruman** [comment]
Okay will do.

**Comment by grahamehorner** [comment]
@TaviTruman I'm also interested in this; any chance of forwarding info my mail is grahame@gabriel-systems.net thanks in advance

**Comment by TaviTruman** [comment]
Yes - I am working to get the code submitted up the GitHub; I've been super busy with start-up stuff but will get back to code this week and over the weekend. I'll also provide a number of examples and some guidance. Give me a few days.

**Comment by yatli** [comment]
Moving this item to our current milestone.

**Comment by grahamehorner** [comment]
Any update?

**Comment by yatli** [comment]
@grahamehorner please check this out: https://github.com/Microsoft/GraphEngine/pull/91
We're starting to work on the support for Service Fabric, Docker Swarm etc.

**Comment by grahamehorner** [comment]
cool thanx @yatli for the update

**Comment by yatli** [comment]
@grahamehorner update: https://github.com/Microsoft/GraphEngine/pull/120 ServiceFabric integration is almost there!

**Comment by yatli** [comment]
SF integration finished. Closing this issue now;
