### ISSUE TITLE
Cell type mismatched : Global.LocalStorage.UseFriendship(Monica.CellID)

### ISSUE THREAD

**Issue by PhanDuc** [microsoft/GraphEngine#7]
Hi,
I followed example Friend Graph and try to understand how Graph Engine work.
First, i try Performance and it was fine : 
```
            long spouse_id = -1;
            long cast_id = -1;
            using (var cm = Global.LocalStorage.UseCharacter(Monica.CellID))
            {
                
                if (cm.Married) // Check if Married true or false
                    Console.WriteLine(cm.Married);
                    spouse_id = cm.Spouse;
                    Console.WriteLine("Spouse Id : " + spouse_id);

                if (cm.Performer != null)
                {
                    cast_id = cm.Performer;
                    Console.WriteLine("Cast ID: " + cast_id);
                }

                
            }

            Console.WriteLine("The Cast of Monica is: ");
            
            using (var ca = Global.LocalStorage.UsePerformer(cast_id))
            {
                Console.WriteLine(ca.Name);
            }
```
After that i try Global.LocalStorage.UseFriendship(Monica.CellID) but i have an error : 

> An unhandled exception of type 'Trinity.Storage.CellTypeNotMatchException' occurred in FriendsCell.dll
> Additional information: Cell type mismatched.
Please help me understand where i wrong and how to fix this error.
Thanks so much !

**Comment by yatli** [comment]
hi PhanDuc,

The entities (and also the accessor) are strongly-typed, which means that you cannot use a Character (a person) object like a Friendship (a kind of hyperedge).

Hint: Try to hack the demo and add an edge from a person to the friendships.

**Comment by PhanDuc** [comment]
Hi @yatli ,
Can you give me more instruction how to add an edge from person to the friendships, please !
I still don't know how to do its.

**Comment by leoxia** [comment]
@PhanDuc Each cell in Graph Engine has a unique cell id. If we want to use the strongly-typed accessor `UseFriendship`, we have to feed in the id of a Friendship cell.

Let's say Rachel, Monica, and Ross are friends. We can create a Friendship cell as following:
```c#
var friendship = new Friendship(new List<long>());
friendship.friends.Add(Rachel.CellID);
friendship.friends.Add(Monica.CellID);
friendship.friends.Add(Ross.CellID);
Global.LocalStorage.SaveFriendship(friendship);
```

Then, we can use the cell accessor to access the Friendship cell:
```c#
using (var f = Global.LocalStorage.UseFriendship(friendship.CellID))
{
    Console.WriteLine("List of cell ids of persons in this frienship:");
    f.friends.ForEach(cellId => Console.WriteLine(cellId));
}
```
