### ISSUE TITLE
How to run a sample on linux command line?

### ISSUE THREAD

**Issue by thinkloop** [microsoft/GraphEngine#73]
Hello,

I built GraphEngine from source on ubuntu 16.04 and tried to start/run the `samples/Friends` project project by doing `./tools/dotnet/dotnet restore ./samples/Friends/Friends.sln`, however I get the error:

> Nothing to do. None of the projects specified contain packages to restore.

How do I run a sample using the linux command line?

**Comment by yatli** [comment]
Hi @thinkloop !

Friends.csproj is for .net framework. Please try this one:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-beta-001509-00</RuntimeFrameworkVersion>
    <AssemblyName>test_name_coreclr</AssemblyName>
    <RootNamespace>test_name</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GraphEngine.CoreCLR" version="1.0.8850"/>
  </ItemGroup>

  <ItemGroup>
    <TslCodegen Include="**/*.tsl" />
    <Compile Remove="Properties/*.cs" />
  </ItemGroup>

</Project>
```

Also, please build the tsl branch for tsl support under Linux.

**Comment by thinkloop** [comment]
Hey Yatli,

Thanks for the reply. When I run `../../tools/dotnet/dotnet restore ./Friends.lnx` with `Friends.lnx` having the contents of what you provided in the previous msg, I get the following messages:

```
  Restoring packages for /home/ubuntu/workspace/GraphEngine/samples/Friends/Friends.lnx...
/home/ubuntu/workspace/GraphEngine/tools/dotnet/sdk/2.0.0-preview1-005823/NuGet.targets(97,5): warning : Dependency specified was Microsoft.NETCore.App (>= 2.0.0-beta-001509-00) but ended up with Microsoft.NETCore.App 2.0.0-preview1-002028-00. [/home/ubuntu/workspace/GraphEngine/samples/Friends/Friends.lnx]/home/ubuntu/workspace/GraphEngine/tools/dotnet/sdk/2.0.0-preview1-005823/NuGet.targets(97,5): error : Unable to resolve 'GraphEngine.CoreCLR (>= 1.0.8850)' for '.NETCoreApp,Version=v2.0'. [/home/ubuntu/workspace/GraphEngine/samples/Friends/Friends.lnx]
  Generating MSBuild file /home/ubuntu/workspace/GraphEngine/samples/Friends/obj/Friends.lnx.nuget.g.props.
  Generating MSBuild file /home/ubuntu/workspace/GraphEngine/samples/Friends/obj/Friends.lnx.nuget.g.targets.
  Writing lock file to disk. Path: /home/ubuntu/workspace/GraphEngine/samples/Friends/obj/project.assets.json
  Restore failed in 724.45 ms for /home/ubuntu/workspace/GraphEngine/samples/Friends/Friends.lnx.
  
  Errors in /home/ubuntu/workspace/GraphEngine/samples/Friends/Friends.lnx
      Unable to resolve 'GraphEngine.CoreCLR (>= 1.0.8850)' for '.NETCoreApp,Version=v2.0'.
  
  NuGet Config files used:
      /home/ubuntu/.nuget/NuGet/NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json
      /home/ubuntu/workspace/GraphEngine/bin/coreclr

```

**Comment by yatli** [comment]
You have to first build the GE core. Please see the build instructions in the readme file. Currently the TSL codegen is in the `tsl` branch so please checkout that branch instead of `master`.

**Comment by thinkloop** [comment]
Are you talking about these build instructions:

> Install libunwind8, g++, cmake and libssl-dev, then execute tools/build.sh. When the build script is executed for the first time, it will download and install the latest CoreCLR 2.0 SDK to tools/dotnet. A nuget package will be built and put at bin/coreclr/GraphEngine.CoreCLR._version_.nupkg. The folder bin/coreclr will be registered as a local NuGet repository and the local package cache for GraphEngine.CoreCLR will be cleared. After the package is built, you can run dotnet restore to use the newly built package.

This is what I have been following. I will try the `tsl` branch - what is tsl?

**Comment by thinkloop** [comment]
To summarize the build instructions:

1. Install libunwind8, g++, cmake and libssl-dev, then execute tools/build.sh
2. run dotnet restore

Correct?

**Comment by yatli** [comment]
@thinkloop yeah, `tools/build.sh` will add the output directory as a local nuget source (and clean the stale packages), so you'll be able to restore it.

**Comment by yatli** [comment]
btw, `tsl` stands for "Trinity Specification Language" (where you define cell types, communication protocols etc.). See: https://github.com/Microsoft/GraphEngine/blob/master/doc/TSL/index.md
