### ISSUE TITLE
Is Graph Engine suitable to use for a non-critical production app?

### ISSUE THREAD

**Issue by thinkloop** [microsoft/GraphEngine#75]

**Comment by yatli** [comment]
@thinkloop sorry for the late reply.
We've been using GE in a few PROD scenarios internally, but I would say that the stability is correlated to the workload. There were bug reports coming from external users (mainly about cell deadlocks) but we've got them fixed. Also the TSL codegen is re-written when we put it on GitHub, so it could use some time to stabilize.

**Comment by yatli** [comment]
Closing this issue now. Feel free to reopen this discussion.
