### ISSUE TITLE
build sample error on linux

### ISSUE THREAD

**Issue by buaasun** [microsoft/GraphEngine#78]
when I ran the command `../../../tools/dotnet/dotnet build` in  `samples/SSSP/SSSP` directory, it failed and show the log like below
``
dotnet/sdk/2.0.0-preview2-005858/Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
``
where can I get `.Net 4.5` for Linux?

**Comment by yatli** [comment]
Hi! Please see: https://github.com/Microsoft/GraphEngine/issues/73

We will add the .NET core project files soon.
