### ISSUE TITLE
The Backend DB store for GraphEngine

### ISSUE THREAD

**Issue by varghesep** [microsoft/GraphEngine#81]
I'm contemplating on using GraphEngine in place of Neo4J for a social app. 

1. I can save data with Neo4J. Can I persist the data with GraphEngine?
2. Can I use Azure Table Storage as the storage database for the GraphEngine?
3. Do I need a VM if I have to host GraphEngine?

**Comment by TaviTruman** [comment]
@varghesep as the Graph Engine code gens C# Classes from the GE TSL so you are free to use a NoSQL Backend with ease. There is no need to serialize from the GE Memory-Cloud to code generated classes and at present the GE does not provide support for any Graph DB Backend. I've been experimenting with DocumentDB in Azure and that seems to work. The GE does support a Workflow in Visual Studio to deploy the GE into Azure VM - so yes, you'll need a VM.
